### ISSUE TITLE
email pre-filled as first name

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/community-portal#102]
When signing up the email gets pre-filled in the "First name" input field as well as the "contact" field. I think the first name input field should be left empty, as we most probably won't get a name back from auth0?

**Comment by dnaluz** [comment]
I just did a clean signup and all the appropriate fields were filled in correctly.

![Screen Shot 2019-11-25 at 1 59 06 PM](https://user-images.githubusercontent.com/2521244/69569530-d95f6580-0f8b-11ea-9246-7d9f921b07c4.png)

What type of login did you use?  We've been testing with google accounts, maybe the data is coming in different with other accounts?

**Comment by MichaelKohler** [comment]
I just used the normal signup. If google/github/fxa provide the name as well, then this is of course not an issue.

**Comment by stripTM** [comment]
I have used Firefox Account and the first name has also been auto-filled with the email.

**Comment by nukeador** [comment]
First name is no longer pre-populated
