### ISSUE TITLE
Minimum width of avatar not enforced

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/community-portal#103]
I just successfully uploaded and saved a 128x128 picture as my avatar, even though the field says "175x175" minimum.

<img width="428" alt="Screenshot 2019-11-25 at 19 51 20" src="https://user-images.githubusercontent.com/330324/69568965-98c81200-0fb4-11ea-8b44-bf5d5f43e17b.png">

**Comment by dnaluz** [comment]
At the moment it is a suggested size and not programatically enforced.  Perhaps we update the copy for now until we add error handling for smaller image sizes.

**Comment by dnaluz** [comment]
PR: https://github.com/mozilla/community-portal/pull/147

**Comment by dnaluz** [comment]
Fix is live!
