### ISSUE TITLE
Renaming username leads to 404

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/community-portal#104]
I renamed my username and after clicking the save button, I got a 404. This is probably because this just does a refresh, and doesn't redirect to the URL including the new username.

<img width="1550" alt="Screenshot 2019-11-25 at 19 52 07" src="https://user-images.githubusercontent.com/330324/69569076-c9a84700-0fb4-11ea-98a1-aa8e86bc9d13.png">

Going to the profile again by clicking my avatar on the top right led me to the right profile page again.

**Comment by dnaluz** [comment]
This fix has been pushed live!  Thanks for the catch @MichaelKohler
