### ISSUE TITLE
Twitter/GitHub/Telegram handles not correctly linked

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/community-portal#106]
The following social media handles are not getting correctly linked:

* GitHub
* Twitter
* Telegram

Example: https://mdmozdev.wpengine.com/members/mkohler2/KohlerSolutions

This possibly also happens for Facebook and LinkedIn, didn't check those. The profile asks for the handles, so the URL prefix should be applied. The Discourse field asks for the URL specifically.

**Comment by dnaluz** [comment]
@MichaelKohler this seems to be related to https://github.com/mozilla/community-portal/issues/57.  We were discussing how we want to handle sorting and asking the user for their social information.  I'll close this issue and continue the conversation in https://github.com/mozilla/community-portal/issues/57
