### ISSUE TITLE
Shares not implemented

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/community-portal#108]
The following "Share" targets are not implemented yet and point to an internal URL:

* Facebook
* Discourse
* Telegram

<img width="1180" alt="Screenshot 2019-11-25 at 22 01 42" src="https://user-images.githubusercontent.com/330324/69577683-d03fba00-0fc6-11ea-9e72-194eaa0482b4.png">

**Comment by dnaluz** [comment]
There is currently a PR https://github.com/mozilla/community-portal/pull/68 that is waiting to get merged in for this
