### ISSUE TITLE
Twitter Share has wrong URL

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/community-portal#109]
When sharing a group, the Twitter share has not a correct URL (should be the full URL including base path):

https://twitter.com/intent/tweet?url=/groups/the-fishing-group/

If it was the correct full URL, it would also get pre-filled in the tweet box. Right now it (for good reasons) doesn't.

**Comment by dnaluz** [comment]
Thanks for finding this @MichaelKohler , I'll fix it before the share PR https://github.com/mozilla/community-portal/pull/68 gets merged in
