### ISSUE TITLE
Link Member count to member tag content

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/community-portal#110]
The member count on the front page could be linked to the "Our members" tab content. At first I wasn't sure how to get to the members until I saw the tab.

<img width="538" alt="Screenshot 2019-11-25 at 22 05 51" src="https://user-images.githubusercontent.com/330324/69577950-607dff00-0fc7-11ea-9c6b-19f56ef76b5b.png">

**Comment by dnaluz** [comment]
@MichaelKohler this is a great idea, a simple addition.  Will make the update!

**Comment by dnaluz** [comment]
PR ready https://github.com/mozilla/community-portal/pull/113
