### ISSUE TITLE
Question about "Meetings" section of groups

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/community-portal#111]
I'm not sure I understand the purpose of the "Meetings" section on a groups' profile. Is this meant as a general description of the group? What if a group has different meeting venues?

**Comment by nukeador** [comment]
Probably we need to adjust wording, that section is about where and when a group meets.

"Meetings" might create the expectation that it's a list of meetings that happened instead.

@lucyeoh do you have a better recommendation on wording here?

**Comment by nukeador** [comment]
This is now "Recent Events" and "Organized Events"
