### ISSUE TITLE
Meetings in Group marked as required even though it's not

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/community-portal#112]
The "Meetings" section has a * next to it, implying that all fields are required. However none of those fields are currently required.

<img width="905" alt="Screenshot 2019-11-25 at 22 10 35" src="https://user-images.githubusercontent.com/330324/69578320-29f4b400-0fc8-11ea-95dd-e00e96157c96.png">

**Comment by dnaluz** [comment]
This is perhaps a UX discussion but at the top of the page * indicates optional information

![Screen Shot 2019-11-25 at 4 12 15 PM](https://user-images.githubusercontent.com/2521244/69578390-66131f00-0f9e-11ea-80a5-c4b6d5c847ea.png)

**Comment by MichaelKohler** [comment]
oh my.. please change that :(

**Comment by dnaluz** [comment]
We can discuss this on our next call with the Mozilla team! Thanks for bringing this up!

**Comment by mcroud** [comment]
Happy to discuss, but for GDPR compliance you should only ask for what is required. So the default should be absolutely necessary, the exception should be optional fields.
