### ISSUE TITLE
Groups: Can't leave a group

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#114]
I see @michaelkohler created a group that for some reason I'm a member (I didn't join it):

https://mdmozdev.wpengine.com/groups/beeeeeeerlin/

I'm trying to click on "Leave group" but nothing happens

**Comment by MichaelKohler** [comment]
yeah, I wanted to add somebody and you were the first person who came to my mind ;)

**Comment by dnaluz** [comment]
Good find will look into it

**Comment by nukeador** [comment]
I left the group and now links to members and events are not working

https://mdmozdev.wpengine.com/groups/beeeeeeerlin/
