### ISSUE TITLE
Groups: Optional informations is marked with wildcard (*)

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#115]
I was confused because in general fields with a wildcard (*) are mandatory in most site, and we are using that for optional fields.

Since most fields are optional we have a lot of * around. Is there a better way to signal required vs optional where there is not that noise and we are super clear on what's optional?

**Comment by dnaluz** [comment]
This was discussed during the design phase if I'm not mistaken and it was decided that we use * to indicate optional fields.  We can discuss this on the call tomorrow.

**Comment by dnaluz** [comment]
Duplicate of this https://github.com/mozilla/community-portal/issues/112

**Comment by mcroud** [comment]
Happy to discuss, but for GDPR compliance you should only ask for what is required. So the default should be absolutely necessary, the exception should be optional fields.

**Comment by mcroud** [comment]
Looking at the ICO website around [data minimisation](https://ico.org.uk/for-organisations/guide-to-data-protection/guide-to-the-general-data-protection-regulation-gdpr/principles/data-minimisation/), it seems the advice I gave regarding this matter is more of a "best practice" than a legal requirement. 
I'll see if I can enquire with one of our privacy engineers on what are sufficient measures

**Comment by mcroud** [comment]
I'll be having a chat with one of our Trust and Security team members on Monday 👍

**Comment by mcroud** [comment]
Yesterday I discussed GDPR form etiquette with our Senior Manager of Trust and Security.
Highlighting the optional fields is fine and compliant however the GDPR does not dictate or prescribe how we make users aware, the only requirement is to make it clear which field are genuinely needed and which are not.

As asterisks use is a common pattern for "Mandatory" fields, we're seeing some understandable confusion so our likely options are:

1. Replace occurrences of the asterisks with: **_optional_** and remove the "*optional" key
2. Separate the mandatory fields from the optional fields, give them clear headers.  
3. Resort to the typical asterisk for mandatory fields pattern.

1 and 3 appeal to me the most, so I'd suggest we try 1 as a quick (...he says) tweak and if there is still confusion resort to 3. How does that sound? happy for feedback :)

**Comment by nukeador** [comment]
@mcroud I think we used to have the "optional" label, but it was super noisy visually because 95% of the fields are optional, so basically you end up on a page full of "optional" labels everywhere.

**Comment by mcroud** [comment]
@nukeador In which case and inlight of my talk with the Trust and Security team; I'm very happy to resort to a more traditional *Mandatory field method 👍

**Comment by dnaluz** [comment]
I'm good with option 3 as it seems to be the "traditional" method.

**Comment by dnaluz** [comment]
@nukeador @mcroud, So as I was going through the code to make the updates to the form labels I noticed that for the profile form we weren't using * to denote optional, we use what @nukeador mentioned (optional).  I think we chose this because of legal.  Should we keep this pattern for the profile and change the other forms to the * denoting required or will this cause confusion with regards to consistency across the other forms?

**Comment by dnaluz** [comment]
Also do we need to identify to the user that * are required fields or do we just update the copy of the current pattern.

**Comment by mcroud** [comment]
Hmm I can't seem to login any more (perhaps the wiping?) but when I tried with a new account the other day I noticed that the Complete Profile page actually used the written word "(required)" which I don't recall being discussed (not that it's a bad thing as it is clear).

I'd definitely recommend using the same pattern throughout the site, so if there was a legal decision to use the word "optional" then that is what we use, however I would be interested to know where the advice came from as it seems a little different to my discussion with Trust & Security 🤔
