### ISSUE TITLE
Avatars loaded from non-secure connection (http)

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#116]
I'm seeing some warning messages on the console about some avatar and images being loaded from non-secure (http) URLs.

**Comment by dnaluz** [comment]
Great catch will create a PR for the fix!

**Comment by dnaluz** [comment]
Looks like there is an issue with wpengine and requesting https.  I'm currently talking with their support team about this

**Comment by dnaluz** [comment]
alright this is fixed for groups and members.

**Comment by dnaluz** [comment]
Events now done as well.
