### ISSUE TITLE
Cookie consent confusion

### ISSUE THREAD

**Issue by mcroud** [mozilla/community-portal#120]
Two things.
Can we underline the Privacy Policy and Cookie Policy links in the consent banner, currently they render exactly as the body copy:

<img width="789" alt="Screenshot 2019-11-27 at 10 39 08" src="https://user-images.githubusercontent.com/42435754/69716615-47c63400-1102-11ea-8e05-ba987d542aa7.png">

Lastly, are we expecting personalised advertising on here?
Regardless of whether I accept or close the banner, the same "gdrp" (should it be gdpr?) cookie appears, I'm going to assume this is to remember that the banner has been cancelled but no other cookie appears?

<img width="536" alt="Screenshot 2019-11-27 at 10 36 37" src="https://user-images.githubusercontent.com/42435754/69716930-02563680-1103-11ea-99eb-0b5d9b865886.png">

**Comment by mcroud** [comment]
Sorry! I now see that we are not filing bugs of this nature yet as we are still in development, please disregard 😅

**Comment by dnaluz** [comment]
@mcroud yeah the cookie is just for remember if the banner has been clicked

**Comment by davesenior** [comment]
We will need some copy for this. I'll bring it up on our call this afternoon.

**Comment by dnaluz** [comment]
Underline added to links!
