### ISSUE TITLE
Not all cards receive hover/focus effect

### ISSUE THREAD

**Issue by mcroud** [mozilla/community-portal#121]
On the homepage, when I mouse over the cards in "Events", each card receives a thicker grey border.

When I scroll down to "Featured Groups", there is no hover effect present when I mouse over the cards:

![Untitled5](https://user-images.githubusercontent.com/42435754/69717253-9d4f1080-1103-11ea-9738-126954a0c20c.gif)

**Comment by mcroud** [comment]
Sorry! I now see that we are not filing bugs of this nature yet as we are still in development, please disregard 😅

**Comment by dnaluz** [comment]
This type of bug is fine to report.  Thanks for catching it @mcroud

**Comment by dnaluz** [comment]
PR: https://github.com/mozilla/community-portal/pull/125

**Comment by dnaluz** [comment]
Fix is live!
