### ISSUE TITLE
Optional City field has no charcter limit

### ISSUE THREAD

**Issue by mcroud** [mozilla/community-portal#122]
In the City (optional) field it is possible to enter a hefty amount of text, perhaps we should cap this.

Wikipedia tells me the longest place name is:

> Krungthepmahanakhon Amonrattanakosin Mahintharayutthaya Mahadilokphop Noppharatratchathaniburirom Udomratchaniwetmahasathan Amonphimanawatansathit Sakkathattiyawitsanukamprasit (176 letters) 
In Thailand.

So maybe 180 is a good maximum? What I have below is 798.
 
<img width="324" alt="Screenshot 2019-11-27 at 11 14 05" src="https://user-images.githubusercontent.com/42435754/69718773-0dab6100-1107-11ea-9072-1ef7f13e43de.png">

<img width="719" alt="Screenshot 2019-11-27 at 11 13 33" src="https://user-images.githubusercontent.com/42435754/69718780-10a65180-1107-11ea-90c3-1641310bfaa4.png">

**Comment by dnaluz** [comment]
Yeah 180 sounds good.  Will implement

**Comment by dnaluz** [comment]
PR https://github.com/mozilla/community-portal/pull/124

**Comment by dnaluz** [comment]
Fix is live!
