### ISSUE TITLE
Login redirects to non-secure connection (http)

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#131]
Today I tried to login and after the Auth0 screen I got redirected to http://mdmozdev.wpengine.com/ which I obviously didn't fill the information because it would travel through a non-secure connection.

Can we make sure that we never serve content and always redirect to https to avoid someone to use a non-secure channel?

Thanks!

**Comment by dnaluz** [comment]
@nukeador did you login then Auth0 redirected you back after a successful login to http instead of https?

**Comment by dnaluz** [comment]
@nukeador talking with wpengine and forcing all requests to https.  This may also be a setting that the Mozilla IT team needs to force on your wpengine instance as well.

**Comment by nukeador** [comment]
> @nukeador did you login then Auth0 redirected you back after a successful login to http instead of https?

Yes, exactly that.

**Comment by dnaluz** [comment]
Ok wpengine is forcing all requests from http to https now!
