### ISSUE TITLE
Different Linkedln Icon on Social Handles Section

### ISSUE THREAD

**Issue by jyotsna17gupta** [mozilla/community-portal#132]
The LinkedIn icon present in Social Handles is quite different than the official one (Reference: https://brand.linkedin.com/downloads )

![Screen Shot 2019-11-28 at 6 11 18 PM](https://user-images.githubusercontent.com/8105936/69807225-c1e1e000-120a-11ea-95c7-f05bf89d4bee.png)

**Comment by davesenior** [comment]
We may want to use the official icons in a design clean up sprint
