### ISSUE TITLE
Having only Icons ( omit text) on the Social Handles Section

### ISSUE THREAD

**Issue by jyotsna17gupta** [mozilla/community-portal#133]
Having only the icons on the social handles section would suffice. We can omit the text associated with each icon. This is my opinion, and of course, it's not a bug.

![Screen Shot 2019-11-28 at 6 11 18 PM](https://user-images.githubusercontent.com/8105936/69807411-3ae13780-120b-11ea-829b-5a2115673840.png)

**Comment by davesenior** [comment]
Thanks. We will be closing this issue for now and revisit with the product team.
