### ISSUE TITLE
Skills and Interest: Adding more items in that Section

### ISSUE THREAD

**Issue by jyotsna17gupta** [mozilla/community-portal#134]
We can let the users add their own skills and interests as we are currently providing limited items.
Also, is it possible to segregate the skills and interests section? Both of there are different on reps portal, and they might expect the same here 

Screenshot from reps portal profile:
![Screen Shot 2019-11-28 at 6 25 56 PM](https://user-images.githubusercontent.com/8105936/69807951-8d6f2380-120c-11ea-9727-3a45f85475ec.png)

Skills and Interest Section:
![Screen Shot 2019-11-28 at 6 22 36 PM](https://user-images.githubusercontent.com/8105936/69807796-31a49a80-120c-11ea-8c22-87369fb102fe.png)

**Comment by dnaluz** [comment]
This was the list given to us by Mozilla.  These can be easily added and removed via the admin panel.  We are using these for testing.
