### ISSUE TITLE
Social Handles: Open Social Links in a new Tab

### ISSUE THREAD

**Issue by jyotsna17gupta** [mozilla/community-portal#135]
When I click on my profile links, the profile gets opened on the same page. I loose the track of the community portal at the very same moment.

![Screen Shot 2019-11-28 at 6 30 05 PM](https://user-images.githubusercontent.com/8105936/69808263-24d47680-120d-11ea-9b07-287953faedc9.png)

**Comment by nukeador** [comment]
We follow best practices with links, and we avoid opening them in a new tab.

**Comment by jyotsna17gupta** [comment]
Aah! in that way, this is expected behavior and you may close this.
