### ISSUE TITLE
Account visibilty: Few public fields aren't displayed when logged out

### ISSUE THREAD

**Issue by jyotsna17gupta** [mozilla/community-portal#136]
Few of my profile fields were set to public, but aren't displayed to everyone (I tried to log out to check my profile)

Steps:
[1] I changed the account visibility to Public( Profile photo, username, First Name)
![Screen Shot 2019-11-28 at 6 43 28 PM](https://user-images.githubusercontent.com/8105936/69809220-4df60680-120f-11ea-84d7-047160a1f366.png)

[2] My profile looks like when logged in:
![Screen Shot 2019-11-28 at 6 47 56 PM](https://user-images.githubusercontent.com/8105936/69809365-a2998180-120f-11ea-9653-37783003563e.png)

[3] After logging out, my profile looks like (First Name and Last Name was expected too):
![Screen Shot 2019-11-28 at 6 48 53 PM](https://user-images.githubusercontent.com/8105936/69809426-be048c80-120f-11ea-9df8-fd552e74d632.png)

**Comment by dnaluz** [comment]
PR: https://github.com/mozilla/community-portal/pull/144

**Comment by dnaluz** [comment]
Fix is live
