### ISSUE TITLE
Events: Hosted by @<username> an expected behavior?

### ISSUE THREAD

**Issue by jyotsna17gupta** [mozilla/community-portal#137]
Is this an expected behavior? I would like to see the name instead. Also, how will this vary wrt the settings of the user? I want to show my name, so I have kept it public. 

![Screen Shot 2019-11-28 at 7 06 38 PM](https://user-images.githubusercontent.com/8105936/69810705-80553300-1212-11ea-9d87-b3a93f0521e9.png)

**Comment by dnaluz** [comment]
PR: https://github.com/mozilla/community-portal/pull/144

**Comment by dnaluz** [comment]
Fix is live
