### ISSUE TITLE
Events: When the event is shared, URL opens in the same tab

### ISSUE THREAD

**Issue by jyotsna17gupta** [mozilla/community-portal#138]
When I try to share the event socially, the respective website (for instance, Twitter) opens in the same tab because of which I lose the track of the community portal. I would prefer it to get opened in the new tab.

![Screen Shot 2019-11-28 at 7 13 15 PM](https://user-images.githubusercontent.com/8105936/69811194-944d6480-1213-11ea-93f9-052e196cb9ca.png)

**Comment by asdofindia** [comment]
I feel like this needs to be separately discussed from #135 

https://ux.stackexchange.com/questions/31579/when-if-ever-should-links-be-opened-in-a-new-window/

I think when clicking share buttons the standard expectation and precedence is in opening that in a new tab. Mozilla's discourse instance has that behavior when sharing Twitter or facebook buttons in share topic.
