### ISSUE TITLE
Events: Report the event link doesn't work

### ISSUE THREAD

**Issue by jyotsna17gupta** [mozilla/community-portal#139]
How can I report any event? Nothing happens when I tried clicking the hyperlink

![Screen Shot 2019-11-28 at 7 23 35 PM](https://user-images.githubusercontent.com/8105936/69811668-96fc8980-1214-11ea-8da4-efe912572102.png)

**Comment by dnaluz** [comment]
Duplciate: https://github.com/mozilla/community-portal/issues/89
