### ISSUE TITLE
Events: RSVP and Cancel RSVP

### ISSUE THREAD

**Issue by jyotsna17gupta** [mozilla/community-portal#140]
1. I created the event, for which I had to RSVP. IMO, anyone who creates the event doesn't need to RSVP explicitly. Maybe we can RSVP them by default.

2. After RSVPing, I tried to cancel it. 'Cancel' can be replaced with 'I'm not going' or something which is more readable to users.

3. While canceling the RSVP, a popup says, 'Are you sure you want to cancel your booking?'
We should replace the term 'booking' with RSVP. or change the whole line with something else.
Possible options:
a) Are you sure you don't want to attend the event?' 
b) I don't want to attend the event

![Screen Shot 2019-11-28 at 7 25 12 PM](https://user-images.githubusercontent.com/8105936/69811821-ee9af500-1214-11ea-8db1-fb2a073e4fc1.png)

**Comment by dnaluz** [comment]
functionally RSVPing a user for their own event may have some unwanted consequences, but perhaps we can just include the creator in the event list.  Will have to discuss with our team here

**Comment by dnaluz** [comment]
https://github.com/mozilla/community-portal/pull/145

**Comment by dnaluz** [comment]
Copy updates applied.  Still need to discuss whether or not we want to display event creator as an attendee

**Comment by dnaluz** [comment]
Fix is live!
