### ISSUE TITLE
Events: Event is displayed in 'Events I'm attending'  section when not RSVP'd

### ISSUE THREAD

**Issue by jyotsna17gupta** [mozilla/community-portal#141]
I created an event but didn't RSVP. It is displayed in the 'Events I'm attending' section'. 
It should be shown only in 'My Events' section.

I haven't RSVPd the event:
![Screen Shot 2019-11-28 at 7 36 33 PM](https://user-images.githubusercontent.com/8105936/69812777-d88e3400-1216-11ea-83cf-9dca61c93ca2.png)

Unexpected behavior:
![Screen Shot 2019-11-28 at 7 36 05 PM](https://user-images.githubusercontent.com/8105936/69812804-e8a61380-1216-11ea-8fd9-24c7ad653b6d.png)

**Comment by dnaluz** [comment]
Could you provide some more details as to how you got to this state?  I just created an event that was not hosted by any group and it did not show up in events I am attending

<img width="1306" alt="Screen Shot 2019-11-28 at 11 19 02 AM" src="https://user-images.githubusercontent.com/2521244/69821229-0a7ca780-11d1-11ea-90b8-9b9480152ef5.png">

But it is showing up in My events tab

<img width="1318" alt="Screen Shot 2019-11-28 at 11 19 10 AM" src="https://user-images.githubusercontent.com/2521244/69821241-14060f80-11d1-11ea-8d3d-9f87d95cf2e0.png">

**Comment by dnaluz** [comment]
Ok looks like I've tracked down the issue to how the RSVP and Cancel RSVP functions work.  Will continue to investigate

**Comment by dnaluz** [comment]
Ok so I will be implementing a fix which should clear this up.  When you cancel your RSVP moving forward the booking item is completely deleted from the back end.  Before when cancelling your RSVP you needed to get it approved by a community manager which isn't the intended functionality .  Couldn't find a way to remedy this with auto approval settings either.  PR coming soon

**Comment by dnaluz** [comment]
https://github.com/mozilla/community-portal/pull/145

**Comment by dnaluz** [comment]
Fix is live
