### ISSUE TITLE
Groups: Events and members links not working

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#142]
Suddenly group links to events and members are redirecting to homepage

https://mdmozdev.wpengine.com/groups/playground-inc/

**Comment by dnaluz** [comment]
There is a bug where these views aren't working if you aren't logged in.  Will make changes how the view is triggerd

**Comment by dnaluz** [comment]
PR: https://github.com/mozilla/community-portal/pull/144

**Comment by dnaluz** [comment]
Fix is live
