### ISSUE TITLE
Profile: Event displayed twice under Recent Events 

### ISSUE THREAD

**Issue by jyotsna17gupta** [mozilla/community-portal#143]
I have created only one event which is displayed twice in my profile under Recent Events section 

[1]  Only one event in 'My Events'
![Screen Shot 2019-11-28 at 7 54 39 PM](https://user-images.githubusercontent.com/8105936/69813844-0eccb300-1219-11ea-8453-d79029c105b6.png)

[2] Displayed twice

![Screen Shot 2019-11-28 at 7 54 59 PM](https://user-images.githubusercontent.com/8105936/69813980-50f5f480-1219-11ea-946e-4880621acbba.png)

**Comment by dnaluz** [comment]
This should be fixed in this issue's PR https://github.com/mozilla/community-portal/issues/141

**Comment by dnaluz** [comment]
I've gone ahead and deleted the RSVPs and cancellations from the back end.  You will no longer see that event in your recent list.  I would refrain from RSVPing and cancelling until this fix is out.

**Comment by dnaluz** [comment]
https://github.com/mozilla/community-portal/pull/145

**Comment by dnaluz** [comment]
Fix is live
