### ISSUE TITLE
Profile: Difference in the content when logged in and logged out

### ISSUE THREAD

**Issue by jyotsna17gupta** [mozilla/community-portal#152]
There's a difference in the content when I view my profile logged in and logged out

My profile when logged out:
![Screen Shot 2019-12-01 at 10 01 18 PM](https://user-images.githubusercontent.com/8105936/69916862-1a70e180-1486-11ea-8be7-034800d502c7.png)

My profile when logged in
![Screen Shot 2019-12-01 at 9 59 50 PM](https://user-images.githubusercontent.com/8105936/69916867-28266700-1486-11ea-8c60-742735318ed8.png)

**Comment by dnaluz** [comment]
Fix is live!
