### ISSUE TITLE
Groups: Filter by

### ISSUE THREAD

**Issue by jyotsna17gupta** [mozilla/community-portal#153]
Only one filter by works: either location or tag. Is this an expected behavior?
It would be great if we can have both the filters working.

![Screen Shot 2019-12-01 at 10 40 07 PM](https://user-images.githubusercontent.com/8105936/69917417-d84a9e80-148b-11ea-9743-21626edfeeeb.png)

**Comment by dnaluz** [comment]
Working on a fix!  Thanks for finding this @jyotsna17gupta

**Comment by dnaluz** [comment]
![Screen Shot 2019-12-02 at 12 07 18 PM](https://user-images.githubusercontent.com/2521244/69979448-5777bb00-14fc-11ea-8f11-b83fa790c5aa.png)

Fix live!

**Comment by jyotsna17gupta** [comment]
This seems like the union of both the filters.
Generally, when I use both the filters, it's for Intersection. 
In this scenario, I will prefer seeing the group located in India with Coding tag

**Comment by dnaluz** [comment]
Ok i think I got it now! update is live
