### ISSUE TITLE
Unaligned content and checkboxes

### ISSUE THREAD

**Issue by kindavishal** [mozilla/community-portal#154]
- Browser and Version
   - 70.0.1 (64-bit) Mozilla Firefox for Ubuntu canonical - 1.0

- Platform (Windows/Linux distro/OSX/Android/iOS) and version
```
         NAME="Ubuntu"
         VERSION="18.04.3 LTS (Bionic Beaver)"
         ID=ubuntu
         ID_LIKE=debian
         PRETTY_NAME="Ubuntu 18.04.3 LTS"
         VERSION_ID="18.04"
```

- Description of bug
   - On the ```username/profile/edit``` page the alignment of the check boxed and it's content aren't aligned on the same line (Check Screenshot)

- How to replicate bug
   - ```Create profile -> Go to edit profile section -> Scroll to the end of page```

- Screenshot
![image](https://user-images.githubusercontent.com/35860774/70139719-1973c600-16b9-11ea-88eb-dffaf0824571.png)

**Comment by dnaluz** [comment]
PR ready https://github.com/mozilla/community-portal/pull/165

**Comment by dnaluz** [comment]
Fix is live!
