### ISSUE TITLE
Problem after upload a new profile photo

### ISSUE THREAD

**Issue by felipez3r0** [mozilla/community-portal#155]
I'm using Firefox 71.0b12 (64-bits) on Linux (Debian 10) and after I try to upload a new photo to my profile (.jpeg - 19kb) I don't receive any feedback about the upload (if it worked or not), the photo don't show up.

When I click on Complete Profile the photo appears in my profile perfectly.

**Comment by felipez3r0** [comment]
Maybe it's something related to permissions, I tried to click with the right button, copied the link to the image, pasted the url in the address bar, and then I had to enter the login/password to access the file.
After that I can see the image in the edit profile page.

**Comment by dnaluz** [comment]
Hmm l may have found the issue to this will have to do some more tests.  Thanks for reporting it!

**Comment by dnaluz** [comment]
I believe the fix for this is live.  Looks like you were correct in the permissions, it was returning a http url instead of https which was causing the access popup.  I think it should be ok now!
