### ISSUE TITLE
Event share button is not working

### ISSUE THREAD

**Issue by felipez3r0** [mozilla/community-portal#156]
I'm using  Firefox 71.0b12 (64-bits) on Linux (Debian 10) and when I click in the "Share" button (at the event detail page) it don't show anything and the scrollbar disappear. I have to reload the page to see the scrollbar again. I tried to share this event: events/open-design-event/

**Comment by dnaluz** [comment]
Hmmm looks like it only happens on on some events, might be a broken element somewhere will look into it.  Thanks for finding!

**Comment by nukeador** [comment]
Is this solved? @felipez3r0 can you check again? Thanks!

**Comment by felipez3r0** [comment]
This event is not there anymore, but I've tried with all the other events, and they are working perfectly :+1:
