### ISSUE TITLE
able to access /wp-admin and eddit/trash events

### ISSUE THREAD

**Issue by Costenslayer** [mozilla/community-portal#157]
by accessing /wp-admin i can access all events edit and even trash them as a standard user
![Screenshot_2019-12-04 Events ‹ Mozilla — WordPress](https://user-images.githubusercontent.com/10689279/70183683-222ac300-16de-11ea-83fa-c9cb717d18e4.png)

**Comment by dnaluz** [comment]
THanks for finding this

**Comment by dnaluz** [comment]
@Costenslayer looks like it was a misconfiguration in the events manager plugin.  This should be disabled for subscribers now!  Good find!
