### ISSUE TITLE
Event link colour is wrong blue

### ISSUE THREAD

**Issue by mcroud** [mozilla/community-portal#158]
Minor point, but the different blue seen here for the web link ( `#0000EE` ) is different to other link blue colours seen on the page ( `#0060DF` )

Design | Live
------------ | -------------
<img alt="Screenshot 2019-12-06 at 09 42 24" src="https://user-images.githubusercontent.com/42435754/70313047-c448c900-180c-11ea-96ee-7d9d8e5cef3c.png"> | <img alt="Screenshot 2019-12-06 at 09 42 17" src="https://user-images.githubusercontent.com/42435754/70313048-c448c900-180c-11ea-9d97-0c66bbcf97ab.png">

**Comment by dnaluz** [comment]
Thanks for reporting, will fix!

**Comment by dnaluz** [comment]
PR ready https://github.com/mozilla/community-portal/pull/165

**Comment by dnaluz** [comment]
Fix is live!
