### ISSUE TITLE
Main menu underline floats above the bottom

### ISSUE THREAD

**Issue by mcroud** [mozilla/community-portal#159]
Testing in Firefox Nightly, the current section marker line in the main menu floats in the air. In the designs it should be placed along the bottom edge of the menu

Design | Live
------------ | -------------
<img alt="Screenshot 2019-12-06 at 09 45 59" src="https://user-images.githubusercontent.com/42435754/70313364-62d52a00-180d-11ea-88e7-939a2ef6882b.png"> | <img alt="Screenshot 2019-12-06 at 09 46 04" src="https://user-images.githubusercontent.com/42435754/70313365-62d52a00-180d-11ea-83f3-168cf2407f63.png">

**Comment by dnaluz** [comment]
![Screen Shot 2019-12-06 at 12 44 24 PM](https://user-images.githubusercontent.com/2521244/70343801-2b26ac00-1826-11ea-9996-3a36500c0c86.png)

On my version of the design it's floating, this is an easy change so we should make a decision on which works best!

**Comment by dnaluz** [comment]
The screenshot on the left is a detached organism in figma.  I just confirmed with the designers that the line should be 2 pixels off of the bottom of the nav.  The reason they gave was when you scroll and hit a white area the underline gets lost if it is flush to the bottom

**Comment by mcroud** [comment]
@dnaluz Cool, happy with that. Thanks!
