### ISSUE TITLE
Groups and People "Search" buttons have grey border

### ISSUE THREAD

**Issue by mcroud** [mozilla/community-portal#160]
On Firefox Nightly, the Blue search button for Groups and People appears to have a grey border. This isn't present on the designs, nor is it on the Events Search button.

<img width="433" alt="Screenshot 2019-12-06 at 09 50 03" src="https://user-images.githubusercontent.com/42435754/70313666-f9095000-180d-11ea-87d7-41aaaef839e6.png">
<img width="487" alt="Screenshot 2019-12-06 at 09 50 38" src="https://user-images.githubusercontent.com/42435754/70313667-f9095000-180d-11ea-9712-91f5101cbfbd.png">

**Comment by dnaluz** [comment]
Good find!

**Comment by dnaluz** [comment]
PR ready https://github.com/mozilla/community-portal/pull/165

**Comment by dnaluz** [comment]
Fix is live!
