### ISSUE TITLE
Visual differences between each section's Search area 

### ISSUE THREAD

**Issue by mcroud** [mozilla/community-portal#161]
On Firefox Nightly, when I navigate between the Events, Groups and People pages I notice that  the elements all exhibit minor variations in spacing, size and type. 

In this animated gif I switch between the pages:

![Untitled5](https://user-images.githubusercontent.com/42435754/70314143-d592d500-180e-11ea-9cda-4608ef2184fd.gif)

Elements that appear to change:
- The vertical position of the magnifying glass icon
- Button size
- Placeholder text capitalisation
- Placeholder text colour

**Comment by dnaluz** [comment]
PR ready https://github.com/mozilla/community-portal/pull/165

**Comment by dnaluz** [comment]
Fix is live!
