### ISSUE TITLE
Main search in header not working

### ISSUE THREAD

**Issue by mcroud** [mozilla/community-portal#162]
Typing anything in the top right search field and pressing enter produces no results. Pressing enter when the field has focus also produces no results or redirection.
Tested on Firefox Nightly.

<img  alt="Screenshot 2019-12-06 at 10 37 47" src="https://user-images.githubusercontent.com/42435754/70316854-76d05a00-1814-11ea-9e1e-e2e0a8788f63.png">

**Comment by dnaluz** [comment]
At the moment we don't have site wide search.  So maybe some kind of design treatment needs to be done to remove the search bar

**Comment by nukeador** [comment]
This should be already solved since we removed the bar.
