### ISSUE TITLE
Typo in message asking users to log in

### ISSUE THREAD

**Issue by mcroud** [mozilla/community-portal#163]
When attempting to view an Event I'm attending when not logged in, the message I receive has a minor typo:

<img alt="Screenshot 2019-12-06 at 10 41 04" src="https://user-images.githubusercontent.com/42435754/70317096-fceca080-1814-11ea-859e-5c5f8d8a3bbd.png">

**Comment by dnaluz** [comment]
Good find!

**Comment by dnaluz** [comment]
PR ready https://github.com/mozilla/community-portal/pull/165

**Comment by dnaluz** [comment]
Fix is live!
