### ISSUE TITLE
Different options between Mobile and Desktop filters

### ISSUE THREAD

**Issue by mcroud** [mozilla/community-portal#164]
When looking at the Events page on mobile, the filter menu provides me with four options. Even when logged out I see an option to view Events I'm Attending and Events I've Organised:

<img width="504" alt="Screenshot 2019-12-06 at 10 44 10" src="https://user-images.githubusercontent.com/42435754/70317420-a5026980-1815-11ea-964a-be833e0294c8.png">

On desktop, I only see the two:

<img width="728" alt="Screenshot 2019-12-06 at 10 44 35" src="https://user-images.githubusercontent.com/42435754/70317445-acc20e00-1815-11ea-88b2-29315d877f1b.png">

**Comment by dnaluz** [comment]
Great find, working on a fix !

**Comment by dnaluz** [comment]
PR ready https://github.com/mozilla/community-portal/pull/165

**Comment by dnaluz** [comment]
Fix is live!
