### ISSUE TITLE
Complete Profile page oddities

### ISSUE THREAD

**Issue by mcroud** [mozilla/community-portal#166]
Tested on Nightly, the privacy drop downs on the profile page do not interact when a user clicks on the downward arrows:

![Untitled5](https://user-images.githubusercontent.com/42435754/70431863-daa58d80-1a75-11ea-88ba-de89dc112a22.gif)

Lastly, checkbox labels do not sit aligned to the checkbox itself:
<img width="582" alt="Screenshot 2019-12-09 at 11 21 04" src="https://user-images.githubusercontent.com/42435754/70431945-0294f100-1a76-11ea-8796-9e1deb7fe779.png">

**Comment by dnaluz** [comment]
Ah yes, this was the same issue with the upload image, I have a solution that I can implement today.  Thanks for catching this @mcroud

**Comment by dnaluz** [comment]
Fix is live
