### ISSUE TITLE
Image uploader is not working on Event creation

### ISSUE THREAD

**Issue by kelimuttu** [mozilla/community-portal#168]
Image is not being uploaded on the event creation page although the specification matches the requirement. There's no indication that an image has been selected, an error message, or anything. It just won't be uploaded. 

Tested on Firefox 71 on Mac.

**Comment by dnaluz** [comment]
This seems to work fine on my local machine, but there are a bunch of fixes coming in the next day.  This should be ok after we push the auth0, discourse and design updates tomorrow!

Thanks for reporting!

**Comment by dnaluz** [comment]
I believe the fix should be live
