### ISSUE TITLE
Events: Provide an attendees count

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#171]
Right now we just have a list of all attendees, but it might be useful to get a quick count at the top.

Original

![imagen](https://user-images.githubusercontent.com/531906/70626114-1716ec00-1c24-11ea-8d7f-8731575d46f0.png)

Proposal

![imagen](https://user-images.githubusercontent.com/531906/70626161-30b83380-1c24-11ea-8dcc-1d5231b02c58.png)

**Comment by dnaluz** [comment]
Implemented on QA!
