### ISSUE TITLE
Admin: Open access to WP dashboard?

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#174]
Am I supposed to be able to use this /wp-admin/ page with my regular account?

It seems I'm able to modify things a regular used should not:

![imagen](https://user-images.githubusercontent.com/531906/70627163-ff406780-1c25-11ea-90b1-27ea0b3c9edb.png)

**Comment by MichaelKohler** [comment]
regression of https://github.com/mozilla/community-portal/issues/157 ?

**Comment by dnaluz** [comment]
So you don't have full access those are just the even back end editor.  There are much more options for admin access, If we want I can redirect all users that are not admins to get redirected, but there isn't much a subscriber can do from this screen besides edit their own events and create new ones.

**Comment by davesenior** [comment]
We should prevent access all together.

**Comment by davesenior** [comment]
For subscriber users/regular accounts.

**Comment by nukeador** [comment]
It seems I can modify way more things I can from the site (tags, categories, set password to events...)

**Comment by dnaluz** [comment]
The tags and categories you are adding aren't used anywhere in the site.  Regardless I have a fix coming that will not let anyone view this page unless they are an administrator.

**Comment by dnaluz** [comment]
Fix is live!
