### ISSUE TITLE
Profiles: Can't upload a photo

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#176]
I tried to upload a 800x800 jpg and I get this error:

"Minimum dimensions: 175 x 175px
https://mdmozdev.wpengine.com/wp-content/uploads/2019/12/8b7e45b39602fbd3f44e8bdf1ac5674d-1.jpg
"

**Comment by dnaluz** [comment]
Interesting little bug, seems to work fine locally but when i tested on the QA server it returned this.  Will look into it, thanks @nukeador !

**Comment by dnaluz** [comment]
Ok I implemented a fix, should be good now!
