### ISSUE TITLE
Privacy Policy Pop-up mentions advertising? 

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/community-portal#177]
Is this pop-up mandatory?

If not, can we remove it?

If yes I will get some copy from legal for it. 

<img width="1404" alt="Screen Shot 2019-12-12 at 10 14 36 AM" src="https://user-images.githubusercontent.com/8070833/70724333-6d3d6b00-1cc8-11ea-99ce-79f42466fdf8.png">

**Comment by dnaluz** [comment]
@LucyeoH  this is the GDRP popup.

**Comment by nukeador** [comment]
This should be already solved since we decided to remove it.
