### ISSUE TITLE
Groups: Wording for discourse section

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#182]
Currently the discourse section is called "Announcements" but this is really a "Discussions" section.

**Comment by nukeador** [comment]
Also the bottom "View more updates" should change to "View more topics"

**Comment by dnaluz** [comment]
Implemented on QA

**Comment by nukeador** [comment]
Was "Announcements" also changed? I still see it here:

https://mdmozdev.wpengine.com/groups/community-portal-qa/

**Comment by dnaluz** [comment]
![Screen Shot 2019-12-13 at 11 47 25 AM](https://user-images.githubusercontent.com/2521244/70816859-5ec18300-1d9e-11ea-9b7b-fff18e6b57f0.png)

Weird, it looks like was cached not sure but it's updated now
