### ISSUE TITLE
Groups: Discourse topics font size and color

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#183]
Right now on the list of topics, it seems the date is more important than the title of the topic itself:

![imagen](https://user-images.githubusercontent.com/531906/70799234-4f940280-1da9-11ea-8d7c-2a4bd01ca4b6.png)

I feel both font size and color should switch and title should be the most relevant item

![imagen](https://user-images.githubusercontent.com/531906/70799286-810cce00-1da9-11ea-89d9-abb6214a59f6.png)

**Comment by dnaluz** [comment]
I will talk with design, I am pretty sure the current state is how it is in the figma file but I agree with you that the option you provided makes more sense

**Comment by dnaluz** [comment]
@nukeador just spoke with design they agree with you to flip the stlyes

**Comment by dnaluz** [comment]
Implemented on QA
