### ISSUE TITLE
Events: Copy share link doesn't feel working

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#185]
Although "Copy share link" when sharing an event works, there is no visual confirmation the copy worked so I kept clicking the button because I though it was not working ;-)

**Comment by dnaluz** [comment]
This will require some design work.

**Comment by dnaluz** [comment]
Actually since we don't have a design I will just update the copy of the button to say Link Copied!

**Comment by dnaluz** [comment]
Implemented on QA
