### ISSUE TITLE
Links to privacy & cookie policy

### ISSUE THREAD

**Issue by stripTM** [mozilla/community-portal#190]
The privacy policy footer popup has the links to "privacy policy" and "cookie policy" empty.

**Comment by dnaluz** [comment]
We currently do not have content for these pages so they haven't been linked yet!

**Comment by Francescaminelli** [comment]
Hi, is this also the case for the links at the bottom of the page under "Mozilla"?

**Comment by nukeador** [comment]
The privacy policy banner was removed, which I think this original issue was about. stripTM can you confirm you don't see this anymore?

Thanks!

**Comment by stripTM** [comment]
![imagen](https://user-images.githubusercontent.com/1289297/72426008-3657ea80-3789-11ea-8d02-55ef7a4d3885.png)
There is no banner but there are the empty links in the footer.
Right?
