### ISSUE TITLE
Events: Broken footer?

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#191]
I seems footer on event pages is for some reason too narrow

![imagen](https://user-images.githubusercontent.com/531906/70908356-4dc97980-200b-11ea-9065-ccdf88723454.png)

**Comment by dnaluz** [comment]
Fixed

**Comment by dnaluz** [comment]
Actually it's not fixed, there is a layout issue on this page

**Comment by dnaluz** [comment]
Should be fixed now!
