### ISSUE TITLE
Footer link to Sign Up / Log In

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#194]
There is a footer link called "Sign Up / Log In" that points to https://mdmozdev.wpengine.com/wp-login

We should probably removed it, as well as "Search" since we don't have site-wide search yet.

**Comment by dnaluz** [comment]
Search has been removed from the header and this menu, i am not sure why we would remove the login sign up link.

**Comment by nukeador** [comment]
Oh, maybe I was confused because I saw the footer link when I was logged-in and also it pointed out to a 404

https://mdmozdev.wpengine.com/wp-login

Maybe fixing that link to work and show "Log out" when you are already logged in?

**Comment by dnaluz** [comment]
I updated the link in the menu so now it doesn't go to a 404 page.  To updated the copy if you are logged in or not will need to be added as a feature.
