### ISSUE TITLE
Singnal external links

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#195]
Is there a visual way for people to understand that some links are pointing to an external site.

I was thinking a little icon on hover, specially for the activities and campaigns menus.

**Comment by Mte90** [comment]
I don't know if it is useful. As it is now the only external links are the social and they ahve already an icon.
The external links are just in campaigns/activities but I don't think that is soemthing very useful.

**Comment by Mte90** [comment]
what do you think @couci?

**Comment by couci** [comment]
So we can do that as its done in Mozilla's wiki for example 
![image](https://user-images.githubusercontent.com/7702955/135461240-b02fa291-c033-4812-941c-ab3d06b61c83.png)
I honestly don't think this is much needed, unless there was a user case in mind when this was made.
@nukeador feel free to reopen this if you feel there is a strong case here.
