### ISSUE TITLE
Country/City option only for offline groups

### ISSUE THREAD

**Issue by deimidis** [mozilla/community-portal#196]
Country and city option on Group creation has to be only open for Offline groups, it isn't clear now that those different options are related.

**Comment by couci** [comment]
But why an online group can't be only in Italy for example?

**Comment by Mte90** [comment]
I agree we do events in italian and we specify the country.
True that for some languages that are across languages the situation is different, but there is online option.

**Comment by couci** [comment]
I think we should keep it as is since there is a use case for online events haveing location example the Italian community
