### ISSUE TITLE
People: Extra padding above the header

### ISSUE THREAD

**Issue by harshil1712** [mozilla/community-portal#200]
While visiting any profile there seems to be an extra padding above the header.
To reproduce go to https://community.mozilla.org/people/harshil1712/ 
Browser: Firefox 71.0
OS: Ubuntu 18.04.3 LTS

![Screenshot_2020-01-09 Community Portal - Mozilla](https://user-images.githubusercontent.com/18901032/72043157-783ee780-32d6-11ea-862b-4170e9ff0a0d.png)

**Comment by dnaluz** [comment]
Fixed!

**Comment by harshil1712** [comment]
Awesome! Thanks!
