### ISSUE TITLE
Group Visibility settings are not remembered

### ISSUE THREAD

**Issue by Mte90** [mozilla/community-portal#201]
If I change the visibility for some group sections as public, save and reopen the edit profile page that value is not remembered so is difficult to understand what is the actual situation.

**Comment by nukeador** [comment]
Are you talking about groups or your profile?

**Comment by Mte90** [comment]
About my profile

**Comment by nukeador** [comment]
Which fields are not remembering the visibility settings? It would be helpful to have a screenshot or a list of steps to reproduce the issue.

Thanks!

**Comment by Mte90** [comment]
The problem is happening in all the group settings of the profile page.
To reproduce just change the settings of the visibility of the first group, save and open again the edit page.
I want that all the groups are visible or the internal settings of every field is quite useless.

**Comment by Mte90** [comment]
I tested now, if I change the value on public on refresh of the page after saving the value is custom

**Comment by Mte90** [comment]
Looking at https://github.com/mozilla/community-portal/pull/221/files# there is a foreach that print all the values but doesn't set the saved one, ex https://github.com/mozilla/community-portal/blob/develop/buddypress/members/single/edit.php#L56

Instead the select of the various section has this control https://github.com/mozilla/community-portal/blob/develop/buddypress/members/single/edit.php#L105

**Comment by dnaluz** [comment]
Yes custom is the default selection.  The top select is just for quickly changing the visibility settings .  I can discuss with the designers on how we want the top selects should act.

**Comment by Mte90** [comment]
Well custom is not clear what is the value right now, so I lost 2 minutes on settings multiple time the value.
Also because there is no consistency with the others dropdown in that page so for me is indeed a bug.
