### ISSUE TITLE
Text requires updating after profile creation

### ISSUE THREAD

**Issue by emmairwin** [mozilla/community-portal#206]
Perhaps you are still planning to update this text, but after I created my profile I got some placeholder text :

 "A message here congratulating the user for creating an account and reiterating the benefits of doing so, helping you to connect with other people who like Mozilla. Also an opportunity to encourage the user to put their new account to good use. "

**Comment by emmairwin** [comment]
![Mozilla_--_Community_Portal_-_2020-01-09_11 18 27](https://user-images.githubusercontent.com/60618/72097686-cc939880-32d1-11ea-80fa-b0275b94c2c0.png)

**Comment by LucyeoH** [comment]
Please update to: 

CONGRATULATIONS!

Your Account has been created! You can keep adding to your profile or dive right in. You are now ready to connect with other users, participate in events and projects, and get involved in the Mozilla community.

**Comment by LucyeoH** [comment]
Hey - the copywriter suggested we flip the last 2 lines. Non-urgent. 

CONGRATULATIONS!

Your Account has been created! You are now ready to connect with other users, participate in events and projects, and get involved in the Mozilla community. You can keep adding to your profile or dive right in.
