### ISSUE TITLE
Community Newsletter Checkbox Bugs

### ISSUE THREAD

**Issue by emmairwin** [mozilla/community-portal#207]
On the 'complete profile page', and edit profile page

Dummy text precedes the Newsletter checkbox 
![Mozilla_--_Community_Portal_-_2020-01-09_11 22 52](https://user-images.githubusercontent.com/60618/72098012-7ecb6000-32d2-11ea-9c56-d257c902b585.png)

Also...

I I selected the 'Sign me up for the Mozilla Community Portal Email checkbox on the 'Complete Profile Page', but when I went to the next screen 'Edit Profile' it was no longer selected. I would expect that checkbox to stay checked between screens.

NOTE: this is all part of the create profile process.

**Comment by emmairwin** [comment]
I also tested, generally, when I edit my profile,, and select the newsletter, it does not save.

**Comment by dnaluz** [comment]
Newsletters are not implemented for the initial beta.  I will be hiding this field for the time being
