### ISSUE TITLE
Apostrophe in my Group Name Show are prefixed by three slashes

### ISSUE THREAD

**Issue by emmairwin** [mozilla/community-portal#209]
![Groups_-_Mozilla_Community_Portal_-_2020-01-09_13 49 44](https://user-images.githubusercontent.com/60618/72107808-01f6b100-32e7-11ea-810b-adf849e465fa.png)

**Comment by emmairwin** [comment]
And one slash on the Edit Group Page
![Groups_-_Mozilla_Community_Portal_-_2020-01-09_13 51 54](https://user-images.githubusercontent.com/60618/72107933-3cf8e480-32e7-11ea-914c-09effa1c29b6.png)

**Comment by emmairwin** [comment]
which transfers over to the Discourse forum

![Latest_Community_Portal_Emma_'s_Test_Group_topics_-_Mozilla_Discourse_-_2020-01-09_13 53 07](https://user-images.githubusercontent.com/60618/72108003-6a459280-32e7-11ea-8f5b-74335380e471.png)

**Comment by davesenior** [comment]
Special character sanitization is being a little too aggressive here. It will be investigated.
