### ISSUE TITLE
Change copy on the account created

### ISSUE THREAD

**Issue by couci** [mozilla/community-portal#213]
Once you create the account you get: "A message here congratulating the user for creating an account and reiterating the benefits of doing so, helping you to connect with other people who like Mozilla. Also an opportunity to encourage the user to put their new account to good use."

I guess we want to change that copy

**Comment by dnaluz** [comment]
duplicate of #206

**Comment by dnaluz** [comment]
The copy in the figma file needs a response from @LucyeoH.  NOt sure if the copy still applies
