### ISSUE TITLE
Picture on profile and group photo appearing wrong

### ISSUE THREAD

**Issue by couci** [mozilla/community-portal#214]
While the picture on my profile appears as it should, on the group contact it crops the upper part of the picture

Also, the group picture appears off.

Ideally, it would be good for the user to be able to crop the picture

Adding screenshot 
![image](https://user-images.githubusercontent.com/7702955/72153122-4482c100-33ad-11ea-900b-eecc4bd843d6.png)

**Comment by davesenior** [comment]
We might have to inform the image px dimension for the end user. 
Alternatively we can add a feature and development change request for a cropping tool.

**Comment by nukeador** [comment]
I don't know if it's easier to avoid re-escalating the image, so if it's not a rectangular ones, just show the original size to avoid cropping.

**Comment by nukeador** [comment]
It seems most groups are facing image size issues:

![imagen](https://user-images.githubusercontent.com/531906/72803769-22abf880-3c4f-11ea-9edb-6227ed5fb83e.png)

**Comment by kycapstick** [comment]
For the time being, we can update the card styles to contain the image so it will show the entire image, but it might leave some weird whitespace.

**Comment by nukeador** [comment]
Probably better to have whitespace than cropped images, I guess.
