### ISSUE TITLE
'Get Started' button does not work

### ISSUE THREAD

**Issue by giuliaguizzardi** [mozilla/community-portal#217]
When clicking the Get Started button while logged in, nothing happens.

**Comment by dnaluz** [comment]
I haven't been informed yet of where the getting start CTA should direct to.

**Comment by nukeador** [comment]
@lucyeOH can you comment on this one?

**Comment by LucyeoH** [comment]
Let's have it point to -> https://community.mozilla.org/events/ (for now)


In the future we might want it to go to campaigns or activities but events seems like the most actionable CTA at the moment.

**Comment by nukeador** [comment]
This should be now solved, please close.
