### ISSUE TITLE
Github and discourse links on footer

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#218]
Link/icons on the footer are not linking anything, they should be:

https://github.com/mozilla/community-portal
https://discourse.mozilla.org/c/community-portal/

**Comment by nukeador** [comment]
It seems other links on footer are also not working #190

**Comment by dnaluz** [comment]
I'm going to move these links into the theme settings

**Comment by dnaluz** [comment]
The other links that do not go anywhere are because we don't have content for them.
