### ISSUE TITLE
Ability to re-assign the connected discourse category for a group

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#219]
We need the ability to change the destination discourse category for some groups, like the curated Reps group, which already has a discourse category:

https://discourse.mozilla.org/c/reps/

**Comment by nukeador** [comment]
Clarification: We might want to do this as ad-hoc need, not something that we will usually do from the admin interface. So if this is something we can request to change on the database it would be highly appreciated, I expect no more than 5-6 groups in this situation.

**Comment by nukeador** [comment]
@LeoMcA will be talking with @dnaluz about this to understand the best approach.

**Comment by LeoMcA** [comment]
Provided none of the [`/categories/`](https://mozilla.github.io/discourse-mozilla-gcm/#tag/Categories) endpoints are called on the non-`/c/community-portal/blah` category, then the api shouldn't spit out any errors.

User addition/removal from the group can still be synced with [`/groups/{id}/users`](https://mozilla.github.io/discourse-mozilla-gcm/#operation/groups#modify_users), and I can manually link that group to the existing discourse category for notification purposes.

The [get a list of topics](https://docs.discourse.org/#tag/Categories/paths/~1c~1%7Bid%7D.json/get) api can be used on any category (as it's ready only).

**Comment by nukeador** [comment]
So if I understand this correctly, changing the destination discourse category ID from the portal shouldn't through any issues.

**Comment by dnaluz** [comment]
@nukeador I don't have access to your production database, so doing an ad-hoc solution is not viable.  Also the way the meta data is stored in a non readable way so updating the data manually would not be easy.  Creating an interface in the admin would be easier, the only thing stored on the wordpress side is the group / category ids, anytime we need to pull data I do a get on the category / group, so I wouldn't need to sync anything on this side.

**Comment by dnaluz** [comment]
As long as the proper cateogry id is used, but there is no way for me to verify which is the "correct" category id. Also you would need to find the id from the discourse side we wouldn't be searching from the portal side for the proper id.
