### ISSUE TITLE
Wrong language in the discussion topic title when creating a new group

### ISSUE THREAD

**Issue by felipez3r0** [mozilla/community-portal#220]
I created a new group:
https://community.mozilla.org/groups/mozilla-brasil/

The discussion topic title was created as: "Über die Kategorie Mozilla Brasil"
I believe it was supposed to be: "About the Mozilla Brasil category"
Discussion topic: https://discourse.mozilla.org/t/uber-die-kategorie-mozilla-brasil

**Comment by nukeador** [comment]
This feels like a discourse issue with caching API. I asked @LeoMcA about this.

@couci also found this issue today

![imagen](https://user-images.githubusercontent.com/531906/72802370-e9be5480-3c4b-11ea-9ef2-ae705cf676e0.png)
