### ISSUE TITLE
Switch country/region list to list within Firefox product to avoid political issue

### ISSUE THREAD

**Issue by irvin** [mozilla/community-portal#227]
Please change the "Country" to "Country or Region", and switch the list to list within Firefox product here*1, according to this best practice suggestion*2, to avoid any political issues.

1) https://searchfox.org/mozilla-central/source/toolkit/locales/en-US/toolkit/intl/regionNames.ftl 
2) https://wiki.mozilla.org/Lists_of_Countries_and_Regions

**Comment by irvin** [comment]
<img width="446" alt="截圖 2020-01-17 下午10 08 31" src="https://user-images.githubusercontent.com/165936/72618390-ec802780-3975-11ea-8939-39171d1feeab.png">

**Comment by nukeador** [comment]
This is the json with codes and names in English:

https://product-details.mozilla.org/1.0/regions/en-US.json

**Comment by irvin** [comment]
notes: 
- the issue still exist on personal profile page (not sure why it's closed)
- we use "location" on most of other places (event / group filter) so location is probably better than country/region.
