### ISSUE TITLE
Add option to "View profile as"

### ISSUE THREAD

**Issue by dannycolin** [mozilla/community-portal#231]
**Step to reproduce**

1. Log in to https://community.mozilla.org
1. Go to your profile page https://community.mozilla.org/people/username/

**Actual Behavior**

The page show the information that is set as "public / everyone"

**Expected Behavior**

I'd like to have an option to show the information depending on the access role of the user who looks at my profile.

It could be a simple `<select>` that let you choose to view your profile as "public", "registered user" or "only me".

**Comment by couci** [comment]
We have now public and registered user
