### ISSUE TITLE
Can use the website without agreeing on CPG

### ISSUE THREAD

**Issue by bacharakis** [mozilla/community-portal#232]
STR: 
1. Login to the website with SSO
2. Close the tab
3. Open the page and Login again
4. Use the website without completing your profiling or agreeing on the CPG

**Comment by dnaluz** [comment]
Good find.  This check is only being applied on the sso login, but should probably be applied on other pages.

@nukeador Which pages should be restricted from being used.  I am assuming that some pages are still visible but not be.  Im guessing you shouldn't be able to create groups / events, but you should be able to view them?  Your input here would be great!

**Comment by nukeador** [comment]
View only is OK.

But unless you accept the CPG you shouldn't be able to create, edit or join any content (event, group, profile)

**Comment by dnaluz** [comment]
@nukeador thanks!

**Comment by dnaluz** [comment]
I should have a solution for this by tomorrow some time

**Comment by dnaluz** [comment]
Live
