### ISSUE TITLE
Group Community Links not working properly

### ISSUE THREAD

**Issue by bobreyes** [mozilla/community-portal#236]
Links will not work properly if not full URLs are indicated. Better if we can have a note or instructions for users to enter the full URL (including "https://") in the fields.

**Comment by dnaluz** [comment]
This is a good idea, also adding in some validation would help.  @mcroud what do you think the best pattern would be to indicate to the user to include http(s) in the URL fields for creating a group?  Should we indicate it for each individual field label or should we just indicate it at the top level of the section where it says Community Links?

**Comment by mcroud** [comment]
@dnaluz This information would also be helpful in other places like the "URL" field within Group Meetings.

Perhaps the pattern should be universal and for each URL field we add a placeholder of "https://" to indicate we are looking for a full URL. Similar to webcompat.com but perhaps without the "example.com":

<img width="505" alt="Screenshot 2020-01-21 at 09 43 22" src="https://user-images.githubusercontent.com/42435754/72793572-8b38ac80-3c32-11ea-85fe-1523e5facde7.png">

I'm thinking something like this perhaps:

<img width="887" alt="Screenshot 2020-01-21 at 09 54 35" src="https://user-images.githubusercontent.com/42435754/72794546-15354500-3c34-11ea-8250-5fa82e50208a.png">

The "Full URLs required" sub heading is the same style as the "min dimensions 703px by 400px" avatar help text.

And yep, a little validation would be brilliant! Thanks both!

**Comment by nukeador** [comment]
Ideally the system should be able to understand that both mozilla.org and https://mozilla.org are URLs so we don't bother users with additional typing if they don't need to.

**Comment by bobreyes** [comment]
> Ideally the system should be able to understand that both mozilla.org and https://mozilla.org are URLs so we don't bother users with additional typing if they don't need to.

Yup! That's what I did at first -- just entered the domain names. And when I viewed my profile, the links were not working properly (link points to say https://community.mozilla.org/facebook.com/username instead of https://www.facebook.com/username).

**Comment by dnaluz** [comment]
If we are going to go down the route of automatically prepending the  URL with the appropriate protocol, are we going to move away from allowing users to just put in their username completing the full URL or should that functionality stay in as well?
