### ISSUE TITLE
Add name to groups and profiles titles

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#238]
Currently the <title> for groups and profiles is empty. It should have the name of the group or the name of the person at the start, similar to what we do on events.

**Comment by nukeador** [comment]
The format should be

Name - Type - Mozilla Community

(Except for groups, that might be redundant)

Examples:

My nice event - Events - Mozilla Community
The awesome group - Mozilla Community
Name Surname - People - Mozilla Community

**Comment by dnaluz** [comment]
Since the first name and last name have visibility settings I suggest we use the user name in the title 

example

username - Mozilla Community Portal

**Comment by nukeador** [comment]
Makes sense, we can improve it in the future and show full name if the person visualizing the profile has permissions to do so.

**Comment by dnaluz** [comment]
Live

![Screen Shot 2020-01-22 at 10 21 19 AM](https://user-images.githubusercontent.com/2521244/72906911-f6e94b00-3d00-11ea-9ea6-6bf160133507.png)
