### ISSUE TITLE
Allow to add Decentralise Social Networks in Social Handles

### ISSUE THREAD

**Issue by ranjithrajv** [mozilla/community-portal#240]
Social handles now allow only to add Centralised Social Networking sites addresses.

There should be a provision to add profiles from Fediverse too, like

- [ ] Matrix https://github.com/mozilla/community-portal/issues/203

- [ ] Masotodon/pleroma

- [ ] Pixelfed

- [ ] Peertube

**Comment by nukeador** [comment]
I'll refer to my comment here:

https://github.com/mozilla/community-portal/issues/230#issuecomment-576645441

I don't think we should optimize for a fixed list but find a way groups can define a few custom links with their own labels.

**Comment by ranjithrajv** [comment]
Not just groups, even individual profiles should have the same provision.

**Comment by ranjithrajv** [comment]
Why is this issue closed? The work is still pending.

**Comment by Mte90** [comment]
assign to me please

**Comment by Mte90** [comment]
and also this one is done
