### ISSUE TITLE
Edit profile button should say "Save Profile" beyond the first visit.

### ISSUE THREAD

**Issue by DPX-designer** [mozilla/community-portal#241]
<img width="1078" alt="Screenshot 2020-01-21 at 14 53 07" src="https://user-images.githubusercontent.com/42435754/72814959-d7e5ad00-3c5d-11ea-8db8-597b58847c66.png">

When you're first prompted to complete your profile after registering, having the button say "Complete Profile" makes sense as we are asking users to complete their profile beyond the basics.

When A user attempts to edit their profile after this occasion however, perhaps the button should read as "Save" or "Save profile" as at that stage the profile may already be "complete".

**Comment by couci** [comment]
This was fixed
