### ISSUE TITLE
Broken Footer Links

### ISSUE THREAD

**Issue by LucyeoH** [mozilla/community-portal#242]
None of the footer links are currently working. Please update accordingly: 

Mozilla

    About ------> https://www.mozilla.org/about/
    Mission------> https://www.mozilla.org/mission/
    Contact Us---> send to: community-portal-staff@discourse.mozilla.org
    Donate -----> https://donate.mozilla.org/
    FAQ --------> https://discourse.mozilla.org/t/mozilla-people-directory-faq/

Sub-footer: 
    Community Participation Guidelines ---> https://www.mozilla.org/en-US/about/governance/policies/participation/
    Legal ------> https://www.mozilla.org/en-US/about/legal/
    Privacy  ----> https://www.mozilla.org/en-US/privacy/

**Comment by dnaluz** [comment]
Fixed
