### ISSUE TITLE
"Share group" button is not in the right position.

### ISSUE THREAD

**Issue by wxie2017** [mozilla/community-portal#247]
The link is
https://community.mozilla.org/groups/mozilla-berlin/
The "Share group" button is out of the button area.
![share-group-button](https://user-images.githubusercontent.com/30563445/72855932-19289c00-3cf4-11ea-967d-f18d68e740c7.png)

**Comment by wxie2017** [comment]
This also happens in the link:
https://community.mozilla.org/groups/mozilla-reps/

**Comment by dnaluz** [comment]
Can we get a bit more information regarding this?  Browser / resolution / OS .  I have checked in OSX on both firefox and chrome browsers and it does not display like this for me.

<img width="841" alt="Screen Shot 2020-01-21 at 9 45 57 PM" src="https://user-images.githubusercontent.com/2521244/72861322-8eb24f00-3c97-11ea-9faf-eec81accfc56.png">

**Comment by wxie2017** [comment]
browser: Firefox 68.4.1esr (64 bit)
OS: Debian GNU/Linux 10 x86_64
display resolution: 1366x768 pixels (361x203 millimeters)
