### ISSUE TITLE
Broken discourse links for non-latin titles

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#248]
Example, the second topic on discourse here:

https://community.mozilla.org/groups/mozilla-israel/

The link points to: https://discourse.mozilla.org/t/topic

It should be: https://discourse.mozilla.org/t/topic/52511/2

**Comment by tomer** [comment]
> Example, the second topic on discourse here:
LOL. I was just about to open an issue for the same link. :smile: 

Thanks!

**Comment by dnaluz** [comment]
Links have been updated
