### ISSUE TITLE
Group listing images are loading the original image

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#251]
I noticed how listing groups is sometimes slow, the reason is that group image thumbnails is loading the original image (full size) the person uploaded.

From other mozilla systems, when you upload any kind of image it gets resized to the max resolution we display it on the site and also it's renamed to a random ID to avoid issues with non-lating chars, spaces and others.

Also for the group listing, it should load a smaller size image to save bandwidth.

**Comment by nukeador** [comment]
Example, this page is loading 5 MB of images:

https://community.mozilla.org/groups/?page=4

**Comment by Mte90** [comment]
As the website is built the various image size are not generated, this in an issue that require a lot of changes to use the native wordpress feature so I think that is better to close the ticket is it outside the scope of a legacy software.
