### ISSUE TITLE
Can not edit group details even though I'm logged in

### ISSUE THREAD

**Issue by krharsh17** [mozilla/community-portal#255]
I tried to edit my group's details after creating it. It worked for 2 times but when I went to update it for the third time, I was redirected back to my group's details page.

Here's a screen recording of the same
![HackSlash - Mozilla Community Portal - Google Chrome 2020-01-22 23-58-19](https://user-images.githubusercontent.com/46624829/72923216-9f84c280-3d74-11ea-9135-3d486aae2d5b.gif)

**Comment by dnaluz** [comment]
Thanks for this bug, currently working on a fix!

**Comment by dnaluz** [comment]
@krharsh17 could you please try editing your group now I just pushed a fix.  Thanks!

**Comment by krharsh17** [comment]
Working perfectly! I'm really impressed by your response! Great job😄
