### ISSUE TITLE
New event link leads to a 404

### ISSUE THREAD

**Issue by krharsh17** [mozilla/community-portal#258]
Clicking on the `organize your own` link leads to a 404 Not Found error page. Also, normally I am signed in, but the 404 page shows no signed-in user.

Screen recording:
![Events - Mozilla Community Portal - Google Chrome 2020-01-23 10-44-34](https://user-images.githubusercontent.com/46624829/72958719-02ef0e80-3dce-11ea-9d0c-0bab994a7376.gif)

**Comment by dnaluz** [comment]
This is currently not what is happening for me.  When I click organize your own it goes to the create event form.

The organize your own link for me links to this https://community.mozilla.org/events/edit-event?action=edit

**Comment by dnaluz** [comment]
I've deployed a fix for this.  You'll need to clear your browser cache but when you're not logged in it will now ask you to do so before creating an event.

Good catch thanks for the find @krharsh17

**Comment by krharsh17** [comment]
What's a better way to contribute to the cause of open internet than to contribute to its best advocate! 😅
