### ISSUE TITLE
Connect Newsletter Blocks to Campaigners Mailing List

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/community-portal#262]
Need to connect the newsletter sign-ups to the salesforce list for campaigners email currently here: https://activate.mozilla.community/newsletter

**Comment by LucyeoH** [comment]
@MichaelKohler do you have code for this?

**Comment by MichaelKohler** [comment]
https://github.com/mozilla/activate.mozilla.community/blob/761d07adf6a313c0f0beecd57ebe88e2c9ec256b/src/components/NewsletterForm.js#L235 (Form) and https://github.com/mozilla/activate.mozilla.community/blob/761d07adf6a313c0f0beecd57ebe88e2c9ec256b/src/components/NewsletterForm.js#L145 (JS). The important parts:

* POST Action: https://www.mozilla.org/en-US/newsletter/
* Hidden fields for some values that need to be sent
* The newsletter ID should probably be the same - I doubt we want to attach another newsletter for the Portal

**Comment by LucyeoH** [comment]
@dnaluz FYI

**Comment by kycapstick** [comment]
Thanks for all this @MichaelKohler  and @LucyeoH! In the process of adding this to the campaigns page, a page for /newsletter, and building it into the signup flow.
