### ISSUE TITLE
UP and Dwon arrow keys on keyboard are not working in chat area.

### ISSUE THREAD

**Issue by wxie2017** [mozilla/community-portal#267]
For example, in page
https://chat.mozilla.org/#/room/#brrrlin:mozilla.org
the focus is on one of the chat message. If you press the UP/DOWN arrow keys ,nothing is happening. I would expect focus is moving up and down in the chat area or at least page is moving up and down. While PgUp and pgDn keys are working.

**Comment by dnaluz** [comment]
These issues are for the community portal page.  Are the up/down keys not working on any of the community portal pages.  https://chat.mozilla.org is not part of the community portal.

**Comment by wxie2017** [comment]
Understood. Then this is the wrong place for this issue. There is no such problem in the community portal page.
Please close this issue.
