### ISSUE TITLE
"join group" button is missing for group page for some groups.

### ISSUE THREAD

**Issue by wxie2017** [mozilla/community-portal#271]
for example:
https://community.mozilla.org/groups/mozilla-china-l10n/

**Comment by wxie2017** [comment]
![join-group-button-missing](https://user-images.githubusercontent.com/30563445/73527631-54427200-444e-11ea-9c31-5f5a5df537d6.png)

**Comment by wxie2017** [comment]
browser: Firefox 68.4.1esr (64 bit)
OS: Debian GNU/Linux 10 x86_64
display resolution: 1366x768 pixels (361x203 millimeters)

**Comment by dnaluz** [comment]
<img width="894" alt="Screen Shot 2020-01-31 at 7 51 50 AM" src="https://user-images.githubusercontent.com/2521244/73540683-9643c780-43fe-11ea-9295-9fb0b6310438.png">

It shows for me on this group. Other groups that have the join button missing are invite only groups.    If you are the creator of the group you will not see a join/leave button either.

**Comment by wxie2017** [comment]
Thanks. I understand. I am the creator.
This issue can be closed.
