### ISSUE TITLE
Provide ical feed for events of a group

### ISSUE THREAD

**Issue by freaktechnik** [mozilla/community-portal#274]
It would be really nice for easy integration with other platforms and keeping track of events in a group in your personal calendar to have an ical feed of the events in a group.

**Comment by couci** [comment]
This is the same as #602

**Comment by freaktechnik** [comment]
Not necessarily, 602 seems to talk about single events, while this is a calendar that you can add, similar to for example public google calendars.

**Comment by couci** [comment]
I am not sure what you mean, like a calendar for all events? Are you thinking of something like a button on this page? https://community.mozilla.org/en/events/

**Comment by freaktechnik** [comment]
All events of a group, like https://community.mozilla.org/en/groups/mozilla-reps-council/?view=events but as an ical file that you can subscribe to.

**Comment by couci** [comment]
got it!

**Comment by Mte90** [comment]
Can I get assigned this?
As the plugin we are using generate ical so I need to investigate a bit

**Comment by couci** [comment]
it's all yours @Mte90

**Comment by Mte90** [comment]
And feature added I am not sure if the button link to the feed is in the right place but I added that feature.
