### ISSUE TITLE
Bad contact email in email change notification emails?

### ISSUE THREAD

**Issue by justdave** [mozilla/community-portal#275]
I just changed the email address on my profile, and it sent me an email to say that had been done.  In the email it says if that was an error to contact 'yourfriend@playgroundinc.com'.  That sounds like it might be the default admin address in the CMS and not one that actually goes somewhere.

**Comment by dnaluz** [comment]
Could you let me know what your username is in the community portal so I can investigate if it actually updated or not.

**Comment by nukeador** [comment]
It's a known issue. We tried to change the admin email but there are some infra email issues we are investigating with IT.

Thanks for reporting.
