### ISSUE TITLE
community.mozilla.org/newsletter

### ISSUE THREAD

**Issue by LucyeoH** [mozilla/community-portal#279]
Create the page **community.mozilla.org/newsletter** that contains only the newsletter sign-up block as seen below. It doesn't need to appear in any navigation but is a very useful thing to have.
 
<img width="726" alt="Screen Shot 2020-02-06 at 3 01 29 PM" src="https://user-images.githubusercontent.com/8070833/73973967-94dc3880-48f1-11ea-85f8-cd128f3c9259.png">

**Comment by nukeador** [comment]
@dnaluz now we have the form ready, let's make sure this page is ready please.

**Comment by dnaluz** [comment]
@nukeador 

https://community.mozilla.org/newsletter/
