### ISSUE TITLE
JS error on adding a new event

### ISSUE THREAD

**Issue by Mte90** [mozilla/community-portal#281]
I filled the various fields but is not possible to create a new event, there is no feedback but in the browser console I see these errors in Firefox and Chrome.

![immagine](https://user-images.githubusercontent.com/403283/74049452-70a55800-49d4-11ea-9950-74bb81ac3479.png)
![immagine](https://user-images.githubusercontent.com/403283/74049464-756a0c00-49d4-11ea-995a-9014d296ab00.png)

**Comment by dnaluz** [comment]
Not sure when this happened.  But I've fixed the issue.  Should be working now
