### ISSUE TITLE
Authentication via e-mail for community.mozilla.org gives a link for mdmozdev.wpengine.com

### ISSUE THREAD

**Issue by SphinxKnight** [mozilla/community-portal#285]
When using the option of logging in with an email address, the email contains a message for mdmozdev.wpengine.com instead of community.mozilla.org

This actually seems like phishing as the domains don't have much in common :(

"Click and confirm that you want to sign in to mdmozdev.wpengine.com. Please sign in using the same web browser that you used to generate this link. The link will expire in fifteen minutes."

* Go to https://community.mozilla.org
* Click login
* Enter an email address and click the option for sending a link
* Check your emails

**Comment by tomahawk-pilot** [comment]
its not fishing per se.  its resolving wp engine since community is hosted in wp engine

**Comment by nukeador** [comment]
Maybe there is a way to get these emails coming from a more mozilla email address, I agree.

**Comment by SphinxKnight** [comment]
The issue is not the email address of the sender (noreply@sso.mozilla.com in this case) but the displayed domain in the object/content of said email.

![image](https://user-images.githubusercontent.com/2413436/74153036-f06b3680-4c0f-11ea-8eff-f62aec2c5d76.png)

**Comment by dnaluz** [comment]
mdmozdev.wpengine.com is the development URL that we used to to development on.  We handed this off to Mozilla IT and they pointed community.mozilla.org to that instance.  This would be something to discuss with Mozilla IT / wpengine support as we don't have access to the wpengine dashboard anymore.

**Comment by jdow** [comment]
Which client ID is this? I think I can change the name of the application and this should hopefully resolve this. What should I set it to?

**Comment by nukeador** [comment]
Name of the application should be: Mozilla Community Portal

Or if url is needed: community.mozilla.org

**Comment by jdow** [comment]
I updated the application name to Mozilla Community Portal. Please report back if this solves the issue.

**Comment by SphinxKnight** [comment]
I can confirm this works. Closing.

Thanks @jdow !
