### ISSUE TITLE
Edit event: Confusing labels to cancel/update

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#286]
Editing an event provides you with these two buttons at the end:

![imagen](https://user-images.githubusercontent.com/531906/74152767-4a1f3100-4c0f-11ea-80d4-2a946bc530f3.png)

I'm confused with the labels, will "Cancel Event" cancel my event or cancel the edition?

I assume it will cancel the edition, so I suggest we just use "Cancel" and "Update" as labels here.

Cheers.

**Comment by nukeador** [comment]
Let's change the copy to the one suggested.

Thanks!

**Comment by kycapstick** [comment]
@nukeador the cancel button starts the process of fully deleting the event. Would it make more sense to change this copy to "Delete Event"? We use "Delete Profile" on the profile edit page.

**Comment by davesenior** [comment]
Use delete event
