### ISSUE TITLE
Assign Timezone by group or by user

### ISSUE THREAD

**Issue by Mte90** [mozilla/community-portal#288]
As example in the reps portal to assign the timezone use the profile data of the user.

Another way to do that is as example if the group is Mozilla Italia all the event associated to that group has the same timezone.

But I think that the first option is more easy to implement and will works without any issues and will avoid everytime to set the timezone.

**Comment by nukeador** [comment]
Why would we need timezone if you can specify your country?

**Comment by Mte90** [comment]
There are countries with more timezones like US or Russia.

**Comment by nukeador** [comment]
But if events use the timezone you have on your browser to store a UTC date and when seeing events you see the translated date/time for your browser timezone, that shouldn't be needed, right?

**Comment by Mte90** [comment]
Well for any time is better to define the timezone, this can maybe during the event creation or showing the event but we have that somewhere.

My idea was to define in the user profile so this settings can be used inside the event.

**Comment by couci** [comment]
But what happens if you go to an event in another time zone? This would confuse things further.

**Comment by Mte90** [comment]
Well as there was written in the Reps portal, there is the timezone of the event and the timezone of the user.
This solution is not confusing at all.

**Comment by Mte90** [comment]
If you open that and mark as p2 I can work on this.

**Comment by couci** [comment]
@Mte90 all yours
