### ISSUE TITLE
problem with research function for people

### ISSUE THREAD

**Issue by Francescaminelli** [mozilla/community-portal#293]
When I was searching a specific username in people the site  gave me back a lot of results that were not always  relate with the username I searched. 

(e.g. https://community.mozilla.org/people/?tag=&location=&u=francesca )

**Comment by dnaluz** [comment]
This should be fixed now.  You will need to do a hard refresh on the page to get the new styles.

![Screen Shot 2020-02-12 at 10 56 11 AM](https://user-images.githubusercontent.com/2521244/74352372-64c7e600-4d86-11ea-96a1-65dce2b0a331.png)
