### ISSUE TITLE
Discourse reply count

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#297]
I see the reply count from discourse is always 0

https://community.mozilla.org/groups/mozilla-hispano/

![imagen](https://user-images.githubusercontent.com/531906/74541913-d8aeed80-4f42-11ea-968c-2e9b08c0002e.png)

"Bienvenidos" topic has 12 replies:

https://discourse.mozilla.org/t/bienvenidos/52442

**Comment by dnaluz** [comment]
This should be fixed now
