### ISSUE TITLE
View more events → Main group page

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#298]
The sidebar link "View more events" on groups is sending to /event/ which turn to be the group main page instead of the events one.

Example:

https://community.mozilla.org/groups/mozilla-colombia/

Link points to: https://community.mozilla.org/groups/mozilla-colombia/events/

**Comment by davesenior** [comment]
This should link to the right view:
[](https://community.mozilla.org/groups/mozilla-colombia/?view=events)

**Comment by davesenior** [comment]
Fixed deployed.
