### ISSUE TITLE
Attend vs Will Not Attend Button on Events

### ISSUE THREAD

**Issue by bobreyes** [mozilla/community-portal#299]
How can we improve the ATTEND and WILL NOT ATTEND buttons in event pages? Initial feedback from members of our community is that they are confused about whether they had clicked on the button already, signifying their intent to attend an event when they see the button that says "ATTEND" -- perhaps change it to "I WILL ATTEND" or "ATTENDING"?

**Comment by nukeador** [comment]
"I will attend" and "I won't attend" seems good for a change.
