### ISSUE TITLE
Feature request: Remove CTA button from the top

### ISSUE THREAD

**Issue by couci** [mozilla/community-portal#306]
Can we remove the CTA button from the top?

**Comment by davesenior** [comment]
Can you specify on which page:

- On the homepage?

Thanks!

**Comment by couci** [comment]
On the activities pages. There are activities that we need 2 CTA buttons. We were able to fix that with the editor but it looks like the general CTA button is always there even when we don't populate it.

**Comment by davesenior** [comment]
Coming in deploy.
