### ISSUE TITLE
Featured image in campaigns gets automatically cropped

### ISSUE THREAD

**Issue by couci** [mozilla/community-portal#314]
When adding a featured image on campaings it gets automatically cropped. There is no indication of what is the right size or an editor.

**Comment by davesenior** [comment]
Hi @couci we will look into adding a note. The featured image is a 1:1 square. The resolution presented at desktop size is 283x283.

**Comment by couci** [comment]
@davesenior we put a 283x283 on the this activity but it still crops it https://community.mozilla.org/?post_type=activity&p=465&preview=true&_thumbnail_id=472

**Comment by davesenior** [comment]
@kycapstick @dnaluz can you advise on what the crop does on the image on upload for campaigns?

**Comment by dnaluz** [comment]
The upload image for campaigns is 283x283, the link you provided is an activity not a campaign.

**Comment by dnaluz** [comment]
Activity images are 703x298
