### ISSUE TITLE
Collapse button looks weird 

### ISSUE THREAD

**Issue by Francescaminelli** [mozilla/community-portal#322]
The collapse button in the "localize Mozilla" activity looks weird
![Screenshot_2020-02-24 Community Portal - Mozilla](https://user-images.githubusercontent.com/58478550/75167622-f1c75380-5725-11ea-8a91-4a327db3999a.png)

**Comment by mcroud** [comment]
Similar odd behaviour seen on mobile:

<img width="462" alt="Screenshot 2020-03-02 at 09 52 25" src="https://user-images.githubusercontent.com/42435754/75665121-93412e80-5c6b-11ea-805b-54e7acd31fb4.png">

**Comment by dnaluz** [comment]
https://github.com/mozilla/community-portal/pull/361

**Comment by dnaluz** [comment]
Fix is live
