### ISSUE TITLE
Breaking bug in Group Description editing

### ISSUE THREAD

**Issue by cseas** [mozilla/community-portal#326]
I was trying to make the Community Participation Guidelines link in the [Mozilla Karnataka](https://community.mozilla.org/groups/mozilla-karnataka-blr/) group description appear as a hyperlink, so I wrapped the link around angular brackets like `<https://..link..>`.

After I clicked Save, perhaps a bug got triggered and broke the page as shown in the screenshot below:
![Selection_066](https://user-images.githubusercontent.com/29686866/75351707-92587780-58ce-11ea-84d2-63a3cf38d6b0.png)

The rest of the website was unaffected but only this particular page seemed to break. I opened the webpage in different devices to confirm the same. The group page is fixed now but please look into what triggered the bug.

Discourse topic: https://discourse.mozilla.org/t/breaking-bug-in-community-portal/54684

**Comment by dnaluz** [comment]
The bug was fixed yesterday.  As for links in the description that is not allowed at the moment.  There maybe a feature down the road to allow markdown in the description but as of right now it does not work
