### ISSUE TITLE
Feature to choose group username

### ISSUE THREAD

**Issue by cseas** [mozilla/community-portal#328]
Is there a way to specify a group's handle instead of the website automatically generating it with the name of the group?

For example, in https://community.mozilla.org/groups/mozilla-karnataka-blr/, can we change the `mozilla-karnataka-blr` to `mozillablr`?

**Comment by davesenior** [comment]
Hi @cseas 
Unfortunately we do not have the ability to assign handles or vanity URLs for groups or events. 
Closing for now, but will be brought up as an enhancement for future releases.

**Comment by cseas** [comment]
Hi @davesenior, thanks for the response!
Can we also mark #327 as an enhancement?
