### ISSUE TITLE
Unable to select multiple tags in Events

### ISSUE THREAD

**Issue by cseas** [mozilla/community-portal#336]
While creating or editing an event, I'm not able to select multiple tags. Only one tag can be selected as of now even though the label says: "Select tag(s) for your event".

Reference event I'm trying to Edit: https://community.mozilla.org/events/hackbout/

**Comment by dnaluz** [comment]
We should change the label for that form, you are no longer allowed to select multiple tags for events.

**Comment by dnaluz** [comment]
Updated
