### ISSUE TITLE
Common Voice activity image vertically 'squished'

### ISSUE THREAD

**Issue by mbransn** [mozilla/community-portal#337]
The image for Common Voice on the Activities landing page and activity page are vertically squished...not sure if this is an upload or implementation issue?

Landing page
<img width="418" alt="Screen Shot 2020-02-27 at 10 44 47 AM" src="https://user-images.githubusercontent.com/18686986/75475848-5f55c880-594e-11ea-9345-7927944e7542.png">

Activity page
<img width="765" alt="Screen Shot 2020-02-27 at 10 44 56 AM" src="https://user-images.githubusercontent.com/18686986/75475857-6250b900-594e-11ea-8400-90e3005ed67b.png">

Original visual is [here](https://drive.google.com/file/d/1M14zdS0IjcXd2i2kGksVKxqWyNKeAVrv/view?usp=sharing), perhaps just needs to be re-uploaded? Screenshot for visual reference:
<img width="512" alt="Screen Shot 2020-02-27 at 10 48 43 AM" src="https://user-images.githubusercontent.com/18686986/75476048-c07d9c00-594e-11ea-9adb-e223d75cff34.png">

**Comment by dnaluz** [comment]
I believe it's the image that was uploaded.  This is the image that is currently being used 

https://community.mozilla.org/wp-content/uploads/2020/02/CV_social_red_purple_x3-703-298.jpg

**Comment by mbransn** [comment]
@dnaluz has this been fixed? production is still rendered wrong and this image should be uploaded in its place: https://drive.google.com/file/d/1M14zdS0IjcXd2i2kGksVKxqWyNKeAVrv/view
