### ISSUE TITLE
Buttons should have hover and focus states

### ISSUE THREAD

**Issue by mcroud** [mozilla/community-portal#341]
<img width="759" alt="Screenshot 2020-03-02 at 09 23 48" src="https://user-images.githubusercontent.com/42435754/75662759-8a4e5e00-5c67-11ea-83b5-a5bdc696221a.png">

- Blue fill (Primary) buttons when hover/focus should adopt a transparent fill with a 1px blue border.
- The reverse should happen to blue outline (secondary) buttons, which become filled on hover/focus.

![Untitled7](https://user-images.githubusercontent.com/42435754/75662981-fd57d480-5c67-11ea-8208-451568bd1147.gif)

- Can we also change the border thickness of the secondary buttons to 1px.

**Comment by dnaluz** [comment]
PR ready

https://github.com/mozilla/community-portal/pull/368
