### ISSUE TITLE
Cards render above mobile menu

### ISSUE THREAD

**Issue by mcroud** [mozilla/community-portal#344]
When the mobile menu is invoked, it is rendered below any cards on the screen:

<img width="465" alt="Screenshot 2020-03-02 at 09 54 41" src="https://user-images.githubusercontent.com/42435754/75665301-de5b4180-5c6b-11ea-8d9e-b32707695dd0.png">

**Comment by dnaluz** [comment]
Has been merged into develop.  Waiting to be pushed to live.

**Comment by dnaluz** [comment]
Fix is live
