### ISSUE TITLE
Tag clickable area does not match the badge

### ISSUE THREAD

**Issue by mcroud** [mozilla/community-portal#346]
![Untitled7](https://user-images.githubusercontent.com/42435754/75666671-1e232880-5c6e-11ea-86fe-5fafc7c15feb.gif)

Can the clickable area of the tag be the whole button, not just the text inside.

Can we have a hover/focus state which matches how interests appear in a user's profile section:
![Untitled7](https://user-images.githubusercontent.com/42435754/75668043-9559bc00-5c70-11ea-9b57-f713e26d47cb.gif)

**Comment by dnaluz** [comment]
Which page is this referring to?

**Comment by mcroud** [comment]
Sorry! That would have been helpful information wouldn't it! 🤦‍♂ 

https://community.mozilla.org/activities/test-firefox-voice/

**Comment by dnaluz** [comment]
So for activities they shouldn't be clickable because we don't have a filter activities by tag option.  So they aren't considered actionable
