### ISSUE TITLE
(Western) Frisian (fy) is missing as a language

### ISSUE THREAD

**Issue by Fjoerfoks** [mozilla/community-portal#349]
(Western) Frisian (fy) is missing as a language under Communication & Interests. 
Since it is in https://www.unicode.org/cldr/charts/latest/supplemental/language_territory_information.html#fy it would be nice to add it to the community portal too.
Spoke to Rúben about this: https://matrix.to/#/!rZkfpTwtxYqPpWTOWt:mozilla.org/$_GPmHKH0t6TENmgoAE-YS4JwNQlYpSP5447szzoLrY0?via=mozilla.org

**Comment by nukeador** [comment]
@dnaluz For some reason there list I linked is not the same we implemented?

**Comment by dnaluz** [comment]
Looks like that entry was missed.  Will add it

**Comment by nukeador** [comment]
Do we have a way to check if other entries are also missing? (doing a diff or similar)

**Comment by dnaluz** [comment]
Negative, the languages are stored in an associative array the only way at the moment is to go one by one.  I can provide the current list if you need it.

**Comment by nukeador** [comment]
Please, can you figure out a way to make sure the current implemented list is containing all languages we want to support? Thanks!

**Comment by dnaluz** [comment]
https://github.com/mozilla/community-portal/pull/360

**Comment by dnaluz** [comment]
Fix is live
