### ISSUE TITLE
Migrate ACF fields from JSON to php code

### ISSUE THREAD

**Issue by Mte90** [mozilla/community-portal#351]
If we want to localize the fields using the WP native systems we need that the files at https://github.com/mozilla/community-portal/tree/master/acf are migrated to php code as https://www.advancedcustomfields.com/resources/register-fields-via-php/

This can help with the localization of the portal and avoid steps on creating a dev environment.

**Comment by nukeador** [comment]
All fields are confirmed to be localizable now. Please reopen if it's not the case.

**Comment by Mte90** [comment]
Looking at the code it isn't true.
As the ticket JSON files https://github.com/mozilla/community-portal/tree/master/acf are still there and the only code mention is the reading of this data https://github.com/mozilla/community-portal/search?q=primary_cta_copy&unscoped_q=primary_cta_copy
So the ACF fields wasn't migrated to php code as the ticket suggest.
Also https://github.com/mozilla/community-portal/tree/master/languages this folder is empty or the file are empty so it isn't localized by files but maybe from the WordPress backend with WPML.
This open again to the fact that we need a database dump https://github.com/mozilla/community-portal/issues/239

**Comment by nukeador** [comment]
We have been doing tests on stage with Spanish language and we are able to localize every string displayed on the frontend, by the po file for UI, or WP-admin panel for menus and content.

Fields on the wp-admin panel don't need to be localized since it will be only used by Community Manangers.

Po files are empty until we integrate them with pontoon int he coming month.

**Comment by Mte90** [comment]
As I can see from this code just the string in frontend can be localized https://github.com/mozilla/community-portal/search?q=%22community-portal%22&unscoped_q=%22community-portal%22&type=Code not ACF fields as this ticket was created for.
So maybe the website is not fully localizable as today.

**Comment by nukeador** [comment]
Custom fields for campaigns and activities are localized from the wp-admin via WPML and the are confirmed to work.

**Comment by Mte90** [comment]
So this ticket at the end wasn't satisfied and for me cannot be closed because the issue persist.
The proposal was to convert all the JSON fields in PHP code so was possible to localize with po/mo like the rest of the template and this is not happening.
To localize now there are 2 ways one inside the backend that is manual and another one that is using po/mo.

As I wrote above now the database dump is very needed https://github.com/mozilla/community-portal/issues/239 to test everything if this localizations are on that.

**Comment by nukeador** [comment]
Sorry I still don't understand what's missing. Can you provide an example on what can't be localized right now? I don't understand why this change is needed if we already can localized everything.

Please see https://mozportalstage.wpengine.com/es/ there is nothing left in English there (ignore the strings, they are just placeholders for testing and shouldn't not represent a proper Spanish localization)

**Comment by Mte90** [comment]
I am not saying that is not localized now, I am saying that the purpose of this ticket wasn't achieved.

The ticket say to convert all the ACF fields from JSON to php code but this didn't happened -> https://github.com/mozilla/community-portal/tree/master/acf

Also, as this localization is not happening in files https://github.com/mozilla/community-portal/tree/master/languages but inside the backend they are saved in the database. Also, as they are in the db and not in files they are not available in Pontoon, that was one of the reasons of this ticket.

So without a database dump as today is not possible to work on this theme and the localization by Pontoon is not possible at 100%.

**Comment by nukeador** [comment]
Yes, we know menus and campaigns/activities content will be localized from the wp-admin. The rest will be on the po file that we will connect with pontoon.

The team agreed that we are OK with this limitation and for now we won't be able to make any additional changes to the site features. We'll see if during the rest of 2020 we get some bandwidth to evaluate how to enable external contributions.
