### ISSUE TITLE
Events: Past Events shows Edit options even after event ended

### ISSUE THREAD

**Issue by kindavishal** [mozilla/community-portal#373]
I can see the option to mark myself as "Will not attend" and "Edit" even after the event had happened/event date had passed. See screenshot below:
![image](https://user-images.githubusercontent.com/35860774/76543818-0f7a1400-64ad-11ea-860f-c315f994a3d0.png)

**Comment by nukeador** [comment]
This is OK since we have just incorporated fields to add the actual number of attendees and goals you can fill after the event happened.
