### ISSUE TITLE
Event page shows only starting date on events

### ISSUE THREAD

**Issue by couci** [mozilla/community-portal#385]
Only the starting date is showing on the events preview on https://community.mozilla.org/events/

This can lead to confusion since they are events that have a past date and appear on the future date.

I would suggest that both start and end day appears on the preview

**Comment by dnaluz** [comment]
Are you using the backend of wordpress to create an event? There is no preview for the normal create form for all users.

**Comment by couci** [comment]
no I meant on the events page, example: 
![image](https://user-images.githubusercontent.com/7702955/77164483-b1eb5600-6ab0-11ea-8227-ffa0016b20ec.png)

That event appears on the future event because the end date is in late March. But it only shows the starting date thus making it confusing

**Comment by couci** [comment]
This is the same as #585
