### ISSUE TITLE
Group matrix placeholder

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#397]
Currently the matrix field is having a placeholder about username

![imagen](https://user-images.githubusercontent.com/531906/77667681-d2b91d00-6f82-11ea-869c-3412da1291a2.png)

This should be roomID or roomAlias, since matrix rooms are handled like reps:mozilla.org or !VIqpqQasdGOBIJGNXN.mozilla.org

**Comment by nukeador** [comment]
Maybe we want to also provide reps:mozilla.org also as an example for the placeholder like:

> _room-alias:domain (i.e reps:mozilla.org)_

**Comment by dnaluz** [comment]
Updated
