### ISSUE TITLE
View more topics incorrect link on non-latin groups

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#416]
It seems the link "View more topics" is not directing to the main category listing on discourse for non-latin groups

https://community.mozilla.org/groups/moztw-mozilla-taiwan-community/

Is pointing to

https://discourse.mozilla.org/t/topic/951

Instead of 

https://discourse.mozilla.org/c/community-portal/moztw-mozilla-taiwan-community/316

**Comment by nukeador** [comment]
This issue is also happening on other latin groups

https://community.mozilla.org/groups/mozilla-hispano/

**Comment by dnaluz** [comment]
So we can't use the name of the group in the link to view more topics because for non latin group names the link is broken.  How would we link to the category with just the ID?

**Comment by nukeador** [comment]
https://discourse.mozilla.org/c/community-portal/ID

Example: https://discourse.mozilla.org/c/community-portal/304

Right now for some reason the link is: https://discourse.mozilla.org/t/topic/52442 ?
