### ISSUE TITLE
Change check box text - campaign RSVP

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/community-portal#421]
When someone RSVP's for a campaign they have the option of logging in with or without an account. 
<img width="520" alt="Screen Shot 2020-04-01 at 9 53 21 AM" src="https://user-images.githubusercontent.com/8070833/78145827-5d749e80-73ff-11ea-8e33-f0e08e09246c.png">

 
If they login without an account the text should read: 

---

Title - Get involved without a user account

Fill out the form below to join this campaign, without creating a user account. 

[name] [last name]
[email]

[ ] I'm okay with Mozilla handling my info as explained in this [Privacy Policy](https://www.mozilla.org/en-US/privacy/websites/).

**Comment by nukeador** [comment]
Also the previous button shouldn't say "RSVP" which is something most non English native don't understand and it's difficult to localize, I think it should also say "Get involved"

**Comment by kycapstick** [comment]
Fixed
