### ISSUE TITLE
Add more then 2 people as manager of a group

### ISSUE THREAD

**Issue by Mte90** [mozilla/community-portal#470]
In our case I want that the group is managed by all our Reps so everyone can manage it and add new events not just 2 of us.

**Comment by nukeador** [comment]
Having 2 contacts per group is part of the programmatic decision we took for this portal. Anyone in the group can already add events.

If you want to discuss about having more than two contacts and why that's important for you, let's open a conversation on community portal discourse.

Thanks!

**Comment by Mte90** [comment]
And if we want like meetup a co host that can edit an event?
Right now only the author can do that.

**Comment by nukeador** [comment]
That is a different request, what I'm hearing is:

"As a portal user I want to additional people to be able to edit an event I've created" 

If that's the case, let's open a new issue to capture that.
