### ISSUE TITLE
People search is not working

### ISSUE THREAD

**Issue by kelimuttu** [mozilla/community-portal#473]
Step to reproduce: 
1. Go to https://community.mozilla.org/people/
2. Use the search field on the top right corner of the page to search for a user
3. The result doesn't seem to match at all with what I'm searching for

![Screenshot_2020-04-17 Community Portal - Mozilla](https://user-images.githubusercontent.com/4922388/79531073-6d48df80-809b-11ea-9cb8-7c393f239094.png)

**Comment by dnaluz** [comment]
Looks like the algorithm used to search here wasn't updated when we fixed the people search.  Thanks for reporting
