### ISSUE TITLE
Group search result is showing events instead of groups

### ISSUE THREAD

**Issue by kelimuttu** [mozilla/community-portal#474]
Step to reproduce:
1. Go to https://community.mozilla.org/groups/
2. Use the search field on the top right corner of the page to search for a group
3. The results are showing events instead of groups

![Screenshot_2020-04-17 Community Portal - Mozilla(1)](https://user-images.githubusercontent.com/4922388/79531164-c0229700-809b-11ea-865b-f6126e7f2e76.png)

**Comment by dnaluz** [comment]
The group in the top right corner is for site wide search.  If you need to search specifically on the groups page you need to use the /groups/ specific search at the top middle of the page

**Comment by kelimuttu** [comment]
I know there are pecific search fields for members, groups, or events. However, if the one on top is a global search, then the result should also include member, group, campaign, etc instead of just event, no?

**Comment by dnaluz** [comment]
It does for me.  The Mozilla team requested that events show first, then groups then members

This is what I see

<img width="1031" alt="Screen Shot 2020-04-17 at 1 50 25 AM" src="https://user-images.githubusercontent.com/2521244/79536348-dace1f00-804d-11ea-97d5-dd4a583b271c.png">

**Comment by kelimuttu** [comment]
You're right. I should've look until the end of  the page. Thanks. I'm closing this one, then.
