### ISSUE TITLE
Events date on profiles and groups displaying wrong date

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#480]
Events small detailed date is wrong for all events in profiles and groups.

https://community.mozilla.org/people/kindavishal/

![imagen](https://user-images.githubusercontent.com/531906/79743133-5822b980-8304-11ea-813d-d7ecb2786a30.png)

https://community.mozilla.org/groups/mozilla-italia/

![imagen](https://user-images.githubusercontent.com/531906/79743213-7dafc300-8304-11ea-8ee3-d9dd6f52b878.png)

**Comment by kycapstick** [comment]
A fix for this issue is being pushed to staging

**Comment by davesenior** [comment]
Online for testing on staging.
