### ISSUE TITLE
Squashed illustration on homepage

### ISSUE THREAD

**Issue by DPX-designer** [mozilla/community-portal#483]
The "Network" illustration is not round on the homepage:

<img width="639" alt="Screenshot 2020-04-21 at 14 11 24" src="https://user-images.githubusercontent.com/42435754/79869892-fdf42800-83d9-11ea-99b0-21a5a7bdd566.png">

It appears a little squashed and should resemble the below example:

<img width="389" alt="Screenshot 2020-04-21 at 14 12 29" src="https://user-images.githubusercontent.com/42435754/79869978-25e38b80-83da-11ea-98a5-b199131b3e54.png">

**Comment by couci** [comment]
This is now fixed
