### ISSUE TITLE
Groups RSS feed redirect loop

### ISSUE THREAD

**Issue by Mte90** [mozilla/community-portal#487]
As example https://community.mozilla.org/groups/mozilla-italia/feed/ get an infinite redirect loop so is not possible to get the rss

**Comment by Mte90** [comment]
Also the rest api doesn't have any endpoint to get the events of a group right now... https://community.mozilla.org/wp-json

**Comment by davesenior** [comment]
We currently don't support RSS. It is something that may be roadmapped for a phase 3 release.

**Comment by Mte90** [comment]
Any updates for this? we are working on our community websites and is not possible to get the list of events.

**Comment by Mte90** [comment]
I see an error with the feed links.
Anyway this include users activity not the group events.

**Comment by Mte90** [comment]
assign to me please
