### ISSUE TITLE
UX amendments. April 2020

### ISSUE THREAD

**Issue by mcroud** [mozilla/community-portal#496]
In making sure that the Community Portal receives the same updates that PMO and other projects do, I have a list of three UX amendments along with accompanying designs:

Figma artwork which shows before and after examples: https://www.figma.com/file/JQ4pRjqoGzDWkH3smWgSPc/Design-Crit-1?node-id=1%3A3 

**1. Modal updates**

<img width="644" alt="Screenshot 2020-04-30 at 10 32 28" src="https://user-images.githubusercontent.com/42435754/80695494-e699f680-8acd-11ea-8ea0-7b0bc8a1b9ca.png">

Showing the share dialogue here, there are a number of little tweaks to how modals should look. The button hover/focus states are also outlined in Figma.

**2. Homepage cards**

<img width="538" alt="Screenshot 2020-04-30 at 10 34 36" src="https://user-images.githubusercontent.com/42435754/80695709-31b40980-8ace-11ea-88e4-8fd1f333343b.png">

Maintaining parity with Mozilla Support and /contribute. Cards now have a different hover/focus styling in which the card scales up slightly and the card title receives an underline.
There are also some minor tweaks to padding.

**3. Checkboxes**

<img width="399" alt="Screenshot 2020-04-30 at 10 36 14" src="https://user-images.githubusercontent.com/42435754/80695855-6b851000-8ace-11ea-8781-b201b8ef1b9d.png">

Let's use the same look and feel for form controls as PMO, starting with the checkboxes.

**Comment by kycapstick** [comment]
All updates have been made on staging with the exception of the second close button on the share modal.
