### ISSUE TITLE
Typo in the Website

### ISSUE THREAD

**Issue by arps18** [mozilla/community-portal#500]
There is a small Spacing Typo in the Report a bug Button.
- Link : [Error](https://community.mozilla.org/campaigns/hunt-from-home-phase-2/)

**Comment by cseas** [comment]
Can you please provide a screenshot or specify where in the page this error is? I'm not able to locate it.

**Comment by greenbrown** [comment]
Maybe this one: https://community.mozilla.org/campaigns/hunt-from-home-phase-2/

<img width="436" alt="Screen Shot 2020-05-23 at 12 04 55 AM" src="https://user-images.githubusercontent.com/49750588/82692025-1bdad400-9c89-11ea-9d82-f06b9caf9329.png">

**Comment by kycapstick** [comment]
Looks like this was a user input error. I've updated the field.
