### ISSUE TITLE
"Update event" doesn't work correctly

### ISSUE THREAD

**Issue by Sav22999** [mozilla/community-portal#505]
The "update event" button doesn't work after you press "edit location details".

![image](https://user-images.githubusercontent.com/32335378/82214319-ef842800-9915-11ea-97f5-c2f500cbe96a.png)

![image](https://user-images.githubusercontent.com/32335378/82214309-eabf7400-9915-11ea-8711-faab922db702.png)

I've noticed that when you press "Edit location details" it clears all (location) fields except "Is this event online ..?". So, if you don't change that select-box, the update doesn't work (because the system detects that option like "do not selected" even if it is).
![image](https://user-images.githubusercontent.com/32335378/82214635-71745100-9916-11ea-98e5-591e0c6cec45.png)

**Comment by cseas** [comment]
Already reported #499

**Comment by Sav22999** [comment]
@cseas Yes, I've seen after I've opened the issue. Anyway, I've added more information about this bug in this issue description

**Comment by kycapstick** [comment]
Thanks @Sav22999 a fix for this bug will be included in our next big update. 

In the meantime, you can get around this error by changing the select labelled "is this event online or on location?" to "physical location" and then back to "online".

**Comment by davesenior** [comment]
This is currently online and being tested in staging

**Comment by dnaluz** [comment]
Fixed on staging
