### ISSUE TITLE
Link to groups country with escape issues

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#511]
If you go to 

https://mozportalstage.wpengine.com/groups/mozilla-brasil/

The top link to Brazil point to:

https://mozportalstage.wpengine.com/%22/groups/?location=BR%22

Additional quotes break the link

**Comment by davesenior** [comment]
#512 https://github.com/mozilla/community-portal/pull/512
Ky has submitted a PR.

**Comment by davesenior** [comment]
Merged
