### ISSUE TITLE
Staging: Listing event by initiative lists all events

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#516]
I got here from the link on an activity

https://mozportalstage.wpengine.com/events/?initiative=382

All events are listed instead of just the localization ones.

**Comment by jveens** [comment]
@nukeador It looks like a `nonce` must be included in the URL for the filter form to properly work. 
The link on the activity may just need to be updated.

This link does filter:
https://mozportalstage.wpengine.com/events/?nonce=6e2a24b283&initiative=382

**Comment by nukeador** [comment]
I got that link from https://mozportalstage.wpengine.com/activities/localize-mozilla/

![imagen](https://user-images.githubusercontent.com/531906/82678401-d5b25000-9c49-11ea-818d-7ba21c8430d9.png)

View more events https://mozportalstage.wpengine.com/events/?initiative=382

**Comment by jveens** [comment]
Ah got it. This will be fixed by PR #518
