### ISSUE TITLE
Staging: Profile picture error after edit profile

### ISSUE THREAD

**Issue by greenbrown** [mozilla/community-portal#519]
https://mozportalstage.wpengine.com/people/21lidyaa/

I had a picture on my profile page before this testing. But, when I try to edit my profile page and save it, my profile picture is gone --I have not changed or added a new profile picture though in this edit profile testing.

Then, I go back to the edit profile section and add a new profile picture. It shows the preview of it, but when I click save, it shows no error notification (other changes are fine) but my profile picture failed to be updated.

**Comment by dnaluz** [comment]
This has been fixed and deployed to staging

**Comment by greenbrown** [comment]
confirmed, thank you @dnaluz!
