### ISSUE TITLE
Attend button not displayed on an event page by default

### ISSUE THREAD

**Issue by cseas** [mozilla/community-portal#520]
The "Attend" button is not displayed on an event page unless a user is signed in.

This creates problems in getting people to mark their attendance because they have no clue they need to be logged in and only then they will see there is an Attend button.

**Expected behaviour:**
Attend button should be visible at all times. If a user is not logged in, the Attend button should prompt for login when clicked.

**Comment by nukeador** [comment]
Yes, already captured here https://github.com/mozilla/community-portal/issues/464
