### ISSUE TITLE
RSVP modal too big on mobile 

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#521]
It seems the modal you get when clicking on RSVP as a non-logged user is not adapting to mobile

![imagen](https://user-images.githubusercontent.com/531906/82696597-9dba0580-9c67-11ea-86fa-e6be3dadc8e9.png)

**Comment by kycapstick** [comment]
Hey @nukeador can you provide the browser and device? I'm not able to replicate this issue on my phone.

**Comment by nukeador** [comment]
Firefox Preview on a 1080p screen Android 10.

**Comment by kycapstick** [comment]
I've been doing some testing and haven't been able to replicate the issue. I'm using BrowserStack for testing which only allows me to use Firefox, not Firefox Preview.

**Comment by nukeador** [comment]
This seems to be solved now.
