### ISSUE TITLE
Staging: on campaign no mailchimp audience

### ISSUE THREAD

**Issue by Francescaminelli** [mozilla/community-portal#522]
When preparing a campaign, there is not button that allows to create a Mailchimp audience with those that RSVP.

**Comment by dnaluz** [comment]
Hi Francesca,

Currently on staging we are using Playgrounds mailchimp (free account) as to not over flow the production mailchimp account and there is already an audience in the account from testing.  We will test this functionality of creating an audience so you don't need to worry about it.

**Comment by dnaluz** [comment]
I just tested this and it created the appropriate mailchimp audience
