### ISSUE TITLE
Staging: Campaign, block, less option for the text

### ISSUE THREAD

**Issue by Francescaminelli** [mozilla/community-portal#523]
When creating a campaign block, in the "copy" space, I have fewer options regarding the text than in the normal website. 

Staging website
![Screenshot_2020-05-25 Edit Post ‹ Mozilla — WordPress](https://user-images.githubusercontent.com/58478550/82831614-30051800-9eb9-11ea-9109-5b88d28466ae.png)

Active website: 

![Screenshot_2020-05-25 Edit Post ‹ Mozilla — WordPress(2)](https://user-images.githubusercontent.com/58478550/82831780-a30e8e80-9eb9-11ea-92fe-b389380ca1bb.png)

**Comment by dnaluz** [comment]
@Francescaminelli The last button on the toolbar (right) will toggle the other options.  Currently it's hidden.

<img width="1367" alt="Screen Shot 2020-05-25 at 2 42 52 PM" src="https://user-images.githubusercontent.com/2521244/82837059-0ab2e280-9e96-11ea-844f-87bfa3d7e887.png">
