### ISSUE TITLE
Staging: images do not appear in activities

### ISSUE THREAD

**Issue by Francescaminelli** [mozilla/community-portal#525]
Images inserted in various parts of the activity do not appear in the published activity.

This is how the published event look: 

![Screenshot_2020-05-26 Mozilla - Community Portal](https://user-images.githubusercontent.com/58478550/82922878-77071200-9f7a-11ea-9d82-578707425494.png)

This is where I added images in the activity

![Screenshot_2020-05-26 Edit Post ‹ Mozilla — WordPress](https://user-images.githubusercontent.com/58478550/82922856-70789a80-9f7a-11ea-9172-e387fe580ba1.png)
![Screenshot_2020-05-26 Edit Post ‹ Mozilla — WordPress(1)](https://user-images.githubusercontent.com/58478550/82922860-71a9c780-9f7a-11ea-8196-9664320cd061.png)
![Screenshot_2020-05-26 Edit Post ‹ Mozilla — WordPress(2)](https://user-images.githubusercontent.com/58478550/82922863-73738b00-9f7a-11ea-8dcc-fc1d5015b6f1.png)

**Comment by davesenior** [comment]
Hi.
Images are currently unsupported in activity post body content.
The only officially supported features are plain text and line breaks for that area of posting.
Here is a screenshot from the design spec.

<img width="387" alt="Screen Shot 2020-05-26 at 11 26 51 AM" src="https://user-images.githubusercontent.com/8965217/82924789-dc430f00-9f4a-11ea-98d3-7ae2e37b3517.png">

**Comment by dnaluz** [comment]
We've just pushed a fix that removes the add media button for the time being.  If this is something we want down the road add images to these sections we will need some design work done.
