### ISSUE TITLE
Staging : Cancel event action needs confirmation message 

### ISSUE THREAD

**Issue by yamamashakaa** [mozilla/community-portal#530]
Current behavior : 1)Events got canceled (disappeared) directly  after clicking the cancel event button.
2) Canceled events got permanently deleted and I could not retrieve them.

Expected behavior :
1) A confirmation message to ask me to confirm the event cancellation  before the event got deleted.
2) Event got canceled temporary, I expected the canceled event to be saved somewhere so I can restored it.

**Comment by dnaluz** [comment]
Fixed on staging
