### ISSUE TITLE
Staging : Not sure about the work of 'Mozilla SSO' button

### ISSUE THREAD

**Issue by mMARUF** [mozilla/community-portal#535]
## Steps to Reproduce:

1. Create a account from  the staging server 10
2. Then, In Edit Profile page, click on the **Mozilla SSO** Button 
3. The button does not work (mouse left click)
4. But, when you try to open the link of the **Mozilla SSO** Button  in a new tab, then it works fine
5. And, in the new tab, we see that we can edit the profile

### Observation:

Not sure if the **Mozilla SSO** Button  is for Edit Profile action or not.

And, also if the the button is for EDIT Profile activity, and it opens in new tab, it should work with mouse left click

![MOZILLASSO Button](https://user-images.githubusercontent.com/45368054/83061670-32b16a00-a07f-11ea-9ee8-423b6c10ec82.gif)

**Comment by dnaluz** [comment]
This should be a link to a document describing the Mozilla SSO.  Will need to get this from someone on the Mozilla team.

**Comment by kycapstick** [comment]
@nukeador do we have a link for this?

**Comment by nukeador** [comment]
Let's link to https://wiki.mozilla.org/IAM/Frequently_asked_questions
