### ISSUE TITLE
Staging : 'Remove File' button is not there while dragging a picture from PC for Profile Picture 

### ISSUE THREAD

**Issue by mMARUF** [mozilla/community-portal#539]
## Steps to Reproduce:

- Create a account from the staging server 10
- Go to the EDIT PROFILE page
- Drag a picture from the PC for profile picture 

### Actual Results:
- The 'Remove File' Button is not there. Though when you upload a picture by clicking on the Profile Photo, we then can see the 'Remove File' Button.

### Expected Results:
- The 'Remove File' Button should also be there when dragging a photo to be set at profile photo
![Profile Picture](https://user-images.githubusercontent.com/45368054/83066604-2204f200-a087-11ea-9d00-3a2f837995dc.gif)

**Comment by dnaluz** [comment]
Fixed applied on staging
