### ISSUE TITLE
Staging: Featured campaign not appearing in the homepage

### ISSUE THREAD

**Issue by Francescaminelli** [mozilla/community-portal#541]
I tried to put a "featured campaign" in the homepage. When using the "test campaign" it worked. When I tried again using one of the old campaign draft (common Voice Sprint) it did not. Note that I:
- Published the campaign
- Change the status of the campaign to active
- Change the end date of the campaign

**Comment by dnaluz** [comment]
Hi @Francescaminelli.  So I found what was happening the end date is not included in our checks so the end date was set to today (05/28/2020).  I made an update to the campaign to change the end date to 05/29/2020 and it is now showing up on the homepage.  Should we make a change to include the current date in the check or leave the current date out.

Thanks

**Comment by Francescaminelli** [comment]
Hi, it would be great we could include the current date in the check. Thank you.

**Comment by dnaluz** [comment]
Fix applied on staging
