### ISSUE TITLE
Spelling mistake in the search bar

### ISSUE THREAD

**Issue by devanshgajjar** [mozilla/community-portal#543]
'R' missing in 'Search' in the search bar.
![Screenshot (478)_LI](https://user-images.githubusercontent.com/37979044/83167153-824e6f00-a12d-11ea-94f7-9e10781cb504.jpg)

**Comment by dnaluz** [comment]
Good find thanks!

**Comment by dnaluz** [comment]
PR https://github.com/mozilla/community-portal/pull/544

**Comment by dnaluz** [comment]
Fixed on staging
