### ISSUE TITLE
Staging: Text formating appearing on the card of campaign

### ISSUE THREAD

**Issue by couci** [mozilla/community-portal#558]
While testing a campaign, text format  appears on the card

![image](https://user-images.githubusercontent.com/7702955/83879026-50489880-a73d-11ea-9597-45758b75a428.png)

Url of page: https://mozportalstage.wpengine.com/campaigns/

**Comment by dnaluz** [comment]
Fix has been applied to staging.  Will be pushing to production shortly

https://mozportalstage.wpengine.com/campaigns/

**Comment by dnaluz** [comment]
Fix has been deployed to both staging and production
