### ISSUE TITLE
Profile description lacks format

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#56]
Created my description assuming format (markdown)

No format is displayed

![imagen](https://user-images.githubusercontent.com/531906/69259695-ed3b4e00-0bbe-11ea-8571-a3faa6a46729.png)

**Comment by dnaluz** [comment]
Currently we do not support markdown anywhere on the site.  If this is something needed we will need to create a feature for it.

**Comment by nukeador** [comment]
@lucyeOH I suspect that we want formatting into both profiles and groups descriptions, since this is something we had on mozillians.org and people might c&p what they have there.

**Comment by nukeador** [comment]
@dnaluz Is it possible to at least respect new lines and paragraphs? Right now everything is converted to a single line.

**Comment by dnaluz** [comment]
@nukeador, Yeah I am working on a fix to convert new lines to break tags.

**Comment by dnaluz** [comment]
@nukeador new lines are now recognized, double new line indicates a new paragraph!
