### ISSUE TITLE
Profiles: Social handlers and urls problems

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#57]
Social handles are not specifying they need to be URLs, maybe we want to just ask for the username and autocomplete urls to avoid broken links from users.

**Comment by davesenior** [comment]
Agreed. I think either approach is good. I prefer to autocomplete the URLs

**Comment by dnaluz** [comment]
@nukeador so is the best way to handle this just ask for their users names in the form and create the URLs ourselves on the public facing page?

**Comment by nukeador** [comment]
Yes, I suspect that's the safest and easiest way to avoid people putting wrong or invalid urls for services we know how to autocomplete. And be clear on the fields we are just asking for the username, not a full url.

**Comment by dnaluz** [comment]
Implemented, if a url is provided it will use the URL for backwards compatibilit, but if not it will create the URL.  The labels on the inputs also indicate username!
