### ISSUE TITLE
Improve Event Search

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/community-portal#574]
I've searched for "reps" on the Past Events view, fully expecting to see last [week's weekly meeting](https://community.mozilla.org/events/reps-weekly-call-04-06-2020/) show up on the first page, but it didn't. How does it get sorted? Should this be sorted by date?

![Capture](https://user-images.githubusercontent.com/330324/84388123-92f9ed00-abe3-11ea-900a-3238da36e04b.PNG)

![Capture2](https://user-images.githubusercontent.com/330324/84388137-98efce00-abe3-11ea-8a76-51bc4cd69463.PNG)

**Comment by davesenior** [comment]
Thanks @MichaelKohler, right now it is showing in chronological by default. It should be reversed for relevance.

**Comment by kycapstick** [comment]
Fixed
