### ISSUE TITLE
Campaigns/Organized Events in Profile should be sorted from newest to oldest

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/community-portal#575]
Currently the campaigns I participated in are sorted by oldest to newest on my profile. I'd say this should be newest to oldest.

![Capture3](https://user-images.githubusercontent.com/330324/84388277-d2283e00-abe3-11ea-85ba-1f17168c9b90.PNG)

**Comment by Mte90** [comment]
a page with the issue and assign to me.

**Comment by Mte90** [comment]
I did a partial fix or events. 
For campaigns I have to study a bit as they are showed based on the order you joined them.
