### ISSUE TITLE
Activity "View more events" link issue

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#576]
From https://community.mozilla.org/activities/answer-support-questions/

On the side bar the link "View more events" link to https://community.mozilla.org/events/?initiative=378&nonce=6103b41781

Instead of https://community.mozilla.org/events/?initiative=378

**Comment by davesenior** [comment]
fixed on staging. Production push soon.

**Comment by kycapstick** [comment]
Fixed in production
