### ISSUE TITLE
Groups: Image upload not working

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#60]
Group image upload is not working when you create a group.

**Comment by dnaluz** [comment]
I just created a group and was able to successfully upload a group image

![Screen Shot 2019-11-20 at 12 03 46 PM](https://user-images.githubusercontent.com/2521244/69260422-de887300-0b8d-11ea-9750-aebd37e7ab52.png)


Using latest firefox 70.0.1.

**Comment by davesenior** [comment]
Hi @nukeador 
Can you use attach info on:
Browser:
OS:
Device type:
Recreation steps:
Behaviour:

A community manager will reach out with info on the reporting method.

**Comment by nukeador** [comment]
This only happens when you are creating the group from

https://mdmozdev.wpengine.com/groups/create/step/group-details/

You can add image after if you edit the group.

Firefox 71 under Linux

**Comment by dnaluz** [comment]
PR https://github.com/mozilla/community-portal/pull/84

Similar fix to the profile image.

**Comment by dnaluz** [comment]
FIx is live.
