### ISSUE TITLE
Staging: Copy from English on activities doesn't copy all the blocks

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#600]
I went into one activity and added Spanish as a new language, when I click on copy from English content, only the title and description is copied, not the rest of the blocks.

![imagen](https://user-images.githubusercontent.com/531906/86482183-bc74e700-bd51-11ea-806b-24126b1e1c15.png)

1. Go to https://mozportalstage.wpengine.com/wp-admin/post-new.php?lang=es&post_type=activity&trid=465&source_lang=en
2. Click on copy from English

**Comment by kycapstick** [comment]
If you select "Overwrite with English content" instead of "Copy Content from English" it will pull everything over from the English Activity. Once everything has copied over, you can update them independently of each other.
