### ISSUE TITLE
"Add to calendar" button

### ISSUE THREAD

**Issue by ffissore** [mozilla/community-portal#602]
It would be nice to have a "add to calendar" button so that I can have an event listed on my calendar with a click, instead of copy-pasting text, and schedule, and description

**Comment by ohiogeek8215** [comment]
👍

**Comment by Mte90** [comment]
This https://github.com/mozilla/community-portal/pull/686 create the feed of a group but I was thinking to of a ical off the specific event.
Assign to me please
