### ISSUE TITLE
Links to events in one language not working

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#612]
1. Go to an event with a preferred language such as https://community.mozilla.org/events/charla-de-webassembly-en-conjunto-con-mozilla-chile/
2. Click on the sidebar Spanish
3. You get directed to https://community.mozilla.org/events/?language=es
4. Events are not properly filtered.

**Comment by dnaluz** [comment]
This works on staging.

**Comment by kycapstick** [comment]
Fixed on production.
