### ISSUE TITLE
Link to events tag not working

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#613]
1. Go to an event with a tag such as https://community.mozilla.org/events/charla-de-webassembly-en-conjunto-con-mozilla-chile/
2. Click on the sidebar Evangelizing & Teaching
3. You get directed to https://community.mozilla.org/events/?tag=Evangelizing%20&%20Teaching
4. Events are not properly filtered.

**Comment by kycapstick** [comment]
The issue here is with the & in the tag. I believe we'd moved to using "and" instead.

**Comment by kycapstick** [comment]
Fixed on staging
