### ISSUE TITLE
Getting a WordPress login page instead of SSO for Community Portal login

### ISSUE THREAD

**Issue by siddhartharao17** [mozilla/community-portal#616]
Hi Community Portal team,

When I hit the "Log In/Sign Up" button to login to the community portal on https://community.mozilla.org/ , I get redirected to the below WordPress login page - https://community.mozilla.org/wp-login.php?action=login - instead of the regular Mozilla SSO page. This is new and seems unusual because earlier I used to get the SSO login page.

Has something changed and is this the new normal?

Thank you!

![Screen Shot 2020-07-15 at 10 35 47 AM](https://user-images.githubusercontent.com/8169998/87577245-70963c00-c687-11ea-9bb1-937b90b6b802.png)

**Comment by MichaelKohler** [comment]
I'm seeing the same. This completely breaks the Community Portal.

**Comment by MichaelKohler** [comment]
This seems to be fixed now.
