### ISSUE TITLE
Groups: Secondary contact is not added as group member

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#63]
Groups: Secondary group contact is not added as group member.

Also it doesn't seem the person I added had to accept being a contact person.

**Comment by dnaluz** [comment]
There is no mechanism for a user to accept being a secondary contact.  This is the intended functionality.  If this is something we want it could be added as a future feature

Members added are considered admins and not people currently.  Again we can add this moving forward if it's something that's needed but as of right now when you add a secondary contact it adds them as an an admin of the group.

![Screen Shot 2019-11-20 at 12 05 40 PM](https://user-images.githubusercontent.com/2521244/69260764-65d5e680-0b8e-11ea-9bda-7f2e79e8cf76.png)

**Comment by nukeador** [comment]
OK, let's put a pin on this one since I think people might be able to abuse adding people as contact without them knowing (even staff members)
