### ISSUE TITLE
URLs with not latin chars are not properly displayed on events

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#630]
See https://community.mozilla.org/en/events/how-you-can-build-your-first-vr-experience-during-times-of-social-distancing/

The event link has some unicode chars that are not property displayed.

**Comment by jveens** [comment]
@nukeador I couldn't find any examples of text inputs that support inputting these types of characters. It's very common for the output of URLS to be encoded in this way. 
Even if I try to copy and past the original external link with the non-latin characters into this textarea on GitHub, it gets encoded in the exact same way. 

To fix things looking too weird on the front-end, I've submitted a PR with a fix for the output (PR #634). But we won't be fixing the encoding.
