### ISSUE TITLE
Group events listing should differentiate from past and upcoming

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#631]
Going to https://community.mozilla.org/groups/mozilla-reps/?view=events

All event are listed and the older ones are first. This is not really helpful.

We would need a way to differentiate past events from upcoming ones, and listing should be from newer to older (not the other way around).

Thanks!

**Comment by nukeador** [comment]
Maybe a quick solution would be to order the even listing from upcoming to past and draw a line before the past events, for visual clarity.

**Comment by kycapstick** [comment]
Added fix to sort group events in reverse chronological order.
