### ISSUE TITLE
Is mapbox working?

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#637]
On https://community.mozilla.org/en/events/fryske-common-voice-ynsprekwike/

Mapbox seems empty

![imagen](https://user-images.githubusercontent.com/531906/88178160-3cdc8880-cc2a-11ea-8b64-6c124339254b.png)

**Comment by kycapstick** [comment]
Looks like it's an issue with the security headers that have been added. I'm getting this error in the console:
