### ISSUE TITLE
Groups: Unverified is not linking anything

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#64]
Groups: Unverified is not linking anything, it should provide a description or link to a description.

**Comment by dnaluz** [comment]
Will link this to 

https://discourse.mozilla.org/t/frequently-asked-questions-portal-edition-faq/43224

Will create jira ticket.

**Comment by dnaluz** [comment]
@nukeador should a verified group also link to this page or is it only the unverified version?

**Comment by dnaluz** [comment]
PR https://github.com/mozilla/community-portal/pull/79

**Comment by nukeador** [comment]
I think both should have this information, so people can understand what those mean, thanks!

**Comment by dnaluz** [comment]
@nukeador thanks!
