### ISSUE TITLE
Events: RSVP not working

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#65]
Getting error: You must request at least one space to book an event.

**Comment by davesenior** [comment]
Hi @nukeador 
Can you provide details:

- are you rsvp'ing to your own event?
-browser? version? OS?

**Comment by kycapstick** [comment]
@davesenior I was able to replicate and it looks like this is tied specifically to group events.

**Comment by nukeador** [comment]
This one fails:

https://mdmozdev.wpengine.com/events/testing-party

This one works:

https://mdmozdev.wpengine.com/events/testing-new-event/

**Comment by dnaluz** [comment]
Fix is live
