### ISSUE TITLE
Campaigns order in the campaign page

### ISSUE THREAD

**Issue by Francescaminelli** [mozilla/community-portal#659]
Past campaigns appears in a random order in the community portal campaigns page, instead than in a chronological order.

![image](https://user-images.githubusercontent.com/58478550/88674160-c63c0100-d0e9-11ea-89dd-63a24521d00c.png)

**Comment by nukeador** [comment]
@kycapstick is this an easy fix?

**Comment by kycapstick** [comment]
Super quick fix.
