### ISSUE TITLE
[Bug] Searching Reps by region

### ISSUE THREAD

**Issue by cseas** [mozilla/community-portal#664]
I'm not sure about the other Community Portal groups but I believe at least in the Mozilla Reps group, everyone should be available in the search results when we filter by location so we can find Reps in our region.

As an example, the below link should show all Reps in India but only shows a couple few:
https://community.mozilla.org/en/groups/mozilla-reps/?view=people&country=IN

My intuition is that it might have something to do with the privacy settings in the profiles and maybe most Reps aren't visible in the location filter because their profile isn't set to public.

To try to resolve this, I tried setting my profile to Public. I set it to Public, hit Save, then Edit just to be sure and I see that it keeps going back to Custom. So that might be another bug.

**Comment by couci** [comment]
Yes that's because of privacy reasons. The location issue was fixed, do you still have issues with it?

**Comment by cseas** [comment]
I see that my profile shows up on the above link now so I'd assume the Public setting doesn't have the bug anymore.

I'll try to bring this to the notice of local Reps around me that they need to set their profile as public to show up in search results. Maybe we can take it up as a notification in the next Reps call too.

Site seems to work as expected now. Thanks!
