### ISSUE TITLE
How to add past events?

### ISSUE THREAD

**Issue by srishti-nema** [mozilla/community-portal#666]
There should be a possible way to add past events conducted under a group on the portal. I tried adding events which were conducted earlier under a group but there is no procedure of doing so apart from filling a form requiring the end date of an event to be after a certain date.

**Comment by couci** [comment]
I can't reproduce this one, it works for me. Do you still face this problem?

**Comment by srishti-nema** [comment]
There was this issue of adding the end date of a particular event after the present date. It works now. Closing this issue. Thanks!
