### ISSUE TITLE
Groups: Empty community links showing up

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#67]
If your group has empty community links, placeholder links are showing up

**Comment by dnaluz** [comment]
Working on this created Jira ticket https://playgroundinc.atlassian.net/jira/software/projects/MOZ/boards/18?selectedIssue=MOZ-259

**Comment by dnaluz** [comment]
PR created https://github.com/mozilla/community-portal/pull/70

**Comment by dnaluz** [comment]
This has been pushed to the QA server
