### ISSUE TITLE
The contrast in the language selection drop-down when creating a new event is not ideal

### ISSUE THREAD

**Issue by alex-mayorga** [mozilla/community-portal#671]
![image](https://user-images.githubusercontent.com/649262/109403676-b4a82980-7956-11eb-93dc-d458475a4283.png)

Might be related to usage of an OS dark theme.

**Comment by gaby2300** [comment]
Please try with a new profile, maybe it's an addon's fault

**Comment by alex-mayorga** [comment]
Not add-on related the same happens in Safe Mode.

Something similar is seen on https://www.bing.com/translator

![image](https://user-images.githubusercontent.com/649262/110065961-4d301680-7d68-11eb-9a1f-c307671f82df.png)

So now I believe this might be a Proton bug...

**Comment by alex-mayorga** [comment]
It is believed to be https://bugzilla.mozilla.org/show_bug.cgi?id=1692593
