### ISSUE TITLE
Spam events in Indonesian spotted

### ISSUE THREAD

**Issue by fauzanalfi** [mozilla/community-portal#674]
There are some spam event written in Indonesian spotted in the Portal. Here are some of them:

- https://community.mozilla.org/en/events/game-garang-2/
- https://community.mozilla.org/en/events/poker-online-idn-poker/
- https://community.mozilla.org/en/events/agen-poker-online-idn-poker/
- https://community.mozilla.org/en/events/poker88-adalah-situs-poker-online-terpercaya-2021/
- https://community.mozilla.org/en/events/strategi-cara-bermain-poker-online-dewapoker/
- https://community.mozilla.org/en/events/masalah-yang-tidak-bisa-diprediksi-dalam-judi-online/

If there's any new spam event, I will drop it in this issue later. For now, better check the system if there's a loophole to let the similar spam contents into the Portal.

**Comment by couci** [comment]
This has been resolved, we are looking on blocking IDs or implementing other spam filter options
