### ISSUE TITLE
Report event button missing in certain events

### ISSUE THREAD

**Issue by Francescaminelli** [mozilla/community-portal#675]
In certain events the "report event" button is missing. 

Screenshot - missing button: 
![image](https://user-images.githubusercontent.com/58478550/116399020-bf811c80-a828-11eb-84d8-aaa7280e7afe.png)

Screenshot - button present: 

![image](https://user-images.githubusercontent.com/58478550/116399239-feaf6d80-a828-11eb-9127-57bb3080b197.png)

**Comment by Mte90** [comment]
assign to me please

**Comment by Mte90** [comment]
https://github.com/mozilla/community-portal/blob/a02e9e0fdcd05f5a74b1f0c798335569543510f5/plugins/events-manager/templates/event-single.php#L553

Looking at the code seems that the button it's there only if:

* group assigned
* report email configured
* user is logged

So my guess is that or the group was assigned but there is a check for it or the user wasn't logged.
Without a link to check I think that this ticket can be closed.

**Comment by Francescaminelli** [comment]
Hi, 

I have a couple of other examples of this, if that would be useful. 

Events with no "report" button: 

https://community.mozilla.org/en/events/ieee-7th-world-forum-on-internet-of-things-wf-iot-2021/
https://community.mozilla.org/en/events/common-voice-july-dataset-ask-me-anything/

**Comment by Mte90** [comment]
Both of them are personal events and not of a group so there is a tiny change to that.
