### ISSUE TITLE
HTML elements are broken

### ISSUE THREAD

**Issue by couci** [mozilla/community-portal#680]
some html elements are broken and the text format doesn't appear as it should
![image](https://user-images.githubusercontent.com/7702955/125083271-7111b900-e0c8-11eb-8e44-c799cf603ac4.png)
**This is how it should look**

![image](https://user-images.githubusercontent.com/7702955/125083345-8dadf100-e0c8-11eb-9bda-f20033f63fda.png)
**This is how it looks now**

There was a fix https://github.com/mozilla/community-portal/pull/673 but apparently didn't do the trick

**Comment by Mte90** [comment]
a page with the issue? so we can see what html tag is missing

**Comment by couci** [comment]
@Mte90 that's one of the pages we see the issue https://community.mozilla.org/en/activities/contributing-to-common-voice/

**Comment by Mte90** [comment]
I don't have the admin access to see what is the html used but I guess that is removing the images and headers.
Can I get the HTML of that section from the backend? So I can do some tests.
To me is more simple to strip html tags like `script` that do a whitelist of tags.

**Comment by couci** [comment]
I still see it broken on the voice page @Mte90

**Comment by Mte90** [comment]
The PR was merged but I don't know if the code was deployed on the server.
There are also various PR assigned to another dev that didn't checked all of them.
