### ISSUE TITLE
Text breaking in middle of the words

### ISSUE THREAD

**Issue by couci** [mozilla/community-portal#681]
The text on the profile description breaks a word in the middle making it hard to read

![image](https://user-images.githubusercontent.com/7702955/125083757-10cf4700-e0c9-11eb-8578-adeef203364f.png)

Link to profile: https://community.mozilla.org/en/people/couci/

**Comment by Mte90** [comment]
there isn't this text in the profile

**Comment by couci** [comment]
you need to be logged in to see it

**Comment by Mte90** [comment]
You can assign to me as I already did a pr for that.
