### ISSUE TITLE
Timezone Error

### ISSUE THREAD

**Issue by bobreyes** [mozilla/community-portal#700]
The "In your timezone" line is a little bit off from the original timings of the event (UTC+8 since I was the one who created it).

![Screen Shot 2021-09-24 at 00 11 23](https://user-images.githubusercontent.com/2232/134544676-fbb2fe03-e87c-4c04-9b33-1e0da9e068f0.png)
![Screen Shot 2021-09-24 at 00 11 32](https://user-images.githubusercontent.com/2232/134544704-c9fc9679-02c4-475e-ada5-034851fe67df.png)

**Comment by couci** [comment]
@Mte90 can you take a look

**Comment by Mte90** [comment]
I will take a look, I did various tests with that and was ok but probably my math skills are not so good 😂

**Comment by bobreyes** [comment]
> I will take a look, I did various tests with that and was ok but probably my math skills are not so good 😂

Maybe you just need more coffee 😂

**Comment by couci** [comment]
I see a fix from @Mte90 for this. @bobreyes is this now fixed?

**Comment by Mte90** [comment]
The code wasn't deployed.
In this repo is not automatically on merge but manually so the fix is not yet on production.

**Comment by bobreyes** [comment]
Where do you set the user's (profile) Timezone from the Community Portal?

It is so weird that the timings for events created by other people are correct. But on the events that I created, there is an offset in the timezone.

**Comment by Mte90** [comment]
In the profile I don't think that is possible.

The bug is still on the website as the fix wasn't deployed yet.
