### ISSUE TITLE
Community building and planning tag doesn't show on profile

### ISSUE THREAD

**Issue by couci** [mozilla/community-portal#709]
On editing my profile: https://community.mozilla.org/en/people/couci I have chosen the "Community building and planning" tag though it doesn't show on my profile page 
![image](https://user-images.githubusercontent.com/7702955/137164051-b22ad638-a367-4149-8c4a-cd8df0360f8a.png)

When I choose other tags they appear
![image](https://user-images.githubusercontent.com/7702955/137164178-84672fbc-2cc5-4fd3-ad84-9bea9cfb650e.png)

**Comment by Mte90** [comment]
This bug doesn't happen on staging https://mozportalstage.wpengine.com/it/people/mte90/... 
Seems that on production the last one is not printed.

**Comment by Mte90** [comment]
So now happens also on staging https://mozportalstage.wpengine.com/en/people/mte90/
I am on this :-)

**Comment by craigcook** [comment]
Fixed in https://github.com/mozilla/community-portal/commit/7239064281a32fd126c8ce05fb3df7731a518fa1 and pushed to production.
![image](https://user-images.githubusercontent.com/205591/155427782-14693f8f-33b7-4971-9496-85753d0af010.png)
