### ISSUE TITLE
Bio/location fields are not shown in public profile

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/community-portal#716]
Even though I have set the bio and location fields to "Public", they do not show up on my public profile in a private browsing window.

![image](https://user-images.githubusercontent.com/330324/143089700-a9f2d27e-7570-4c77-a81f-99c8bc3112fb.png)

![image](https://user-images.githubusercontent.com/330324/143089772-07852f57-219c-406a-822d-aab14f34ec33.png)

**Comment by Mte90** [comment]
In my profile they are showed https://community.mozilla.org/en/people/mte90/ also I see them on your profile https://community.mozilla.org/en/people/mkohler/ (as non logged).

**Comment by MichaelKohler** [comment]
Definitely wasn't there when I filed, but now it's looking good. So I'm closing this.
