### ISSUE TITLE
Groups: Past events not visibile

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#72]
How can I see past events from a group?

The one I created is not listed:

https://mdmozdev.wpengine.com/groups/mozillians-valladolid/events/

https://mdmozdev.wpengine.com/events/our-first-meeting

**Comment by davesenior** [comment]
list chronologically, newest first. With older events.

**Comment by dnaluz** [comment]
PR created https://github.com/mozilla/community-portal/pull/80
