### ISSUE TITLE
Showing upcoming events?

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/community-portal#720]
I just created https://community.mozilla.org/en/events/fosdem-22-mozilla-devroom/, however I noticed that this is not showing up in my profile. Do we not show upcoming events? If so, I think it would be great if we did that.

**Comment by Mte90** [comment]
I see that is in the organized events list in the profile https://community.mozilla.org/en/people/mkohler/
There is the issue that recent events is not ordered...

**Comment by MichaelKohler** [comment]
Mh, not sure why it didn't show up. I just created an upcoming test event and it is shown in "Organized events" now. Not perfect naming, as it also shows upcoming events, but that's probably fine. Closing this one then..
