### ISSUE TITLE
I will attend button doesn't work

### ISSUE THREAD

**Issue by couci** [mozilla/community-portal#729]
When trying to click the "I will attend" button on an event page nothing happens.

**Comment by Mte90** [comment]
So I tested and works, I need to know what is the event.

**Comment by bobreyes** [comment]
Experienced the same with https://community.mozilla.org/en/events/mozilla-reps-asean-meetup-2022/ today.

**Comment by Mte90** [comment]
In this ticket is not possible to replicate, I think that the issue happens with events that defined a expire date too much earlier.
Maybe with events created after the last update.
To work on this I need some other cases.

**Comment by couci** [comment]
@Mte90 do you think that this happens to only events that their start date has passed? If yes then can we debug it for those?
I see two cases:
- if both start and end date passed then the button should be "I attended" and be added at events
- if the start date passed but the end date didn't, then the button should remain I will attend. Example of this case where I can reproduce: https://community.mozilla.org/en/events/support-fr-2022-03/#em-booking

**Comment by Mte90** [comment]
There is a setting in the backend area that define the date where is possible to join the event.
As example in this one is 
![immagine](https://user-images.githubusercontent.com/403283/158396976-81bce866-dca9-4ecb-805b-92f950f409b1.png)
So as this date is already over is not possible to attend the event.
My guess is that new events created after the last updates have this value set with the opening date of the event and this doesn't make sense.
I am studying how to workaround this automatically using the end date of the event.

**Comment by Mte90** [comment]
I asked to the plugin support how to do it because as reading the code I don't find anything helpful https://wordpress.org/support/topic/force-a-specific-event_rsvp_date-with-an-hook/

A solution could be that only new event will have the right date set automatically for this field but not the previous ones. So I am looking for something that we can apply everywhere to avoid those cases.

**Comment by Mte90** [comment]
I should be able to fix it :-)

**Comment by Francescaminelli** [comment]
Hi @Mte90 there is still a problem with past events, we cannot sign in if they have already started.

**Comment by Mte90** [comment]
Can I have some examples?

**Comment by Mte90** [comment]
Yes it is not possible to attend an expired event.
The last changes let to attend the event until the end but for the past with the issue right now this means modify a parameter in the wordpress backend area in every event with the issue to a future date, so people can attend them.
The ideal solution it is not to show the "I will attend" button on past event to avoid confusions.

**Comment by couci** [comment]
But the problem doesn't appear only to events that are running but to also events that are starting soon or to events that run for days

**Comment by Mte90** [comment]
@couci I fixed the issue for attend events a week ago, so if it is still happening I need examples...

**Comment by couci** [comment]
Example: https://community.mozilla.org/en/events/this-is-a-test/ I created this one. It starts in 20 min so logically I should be able to attend. Still @Francescaminelli tried and the "I will attend button" doesn't work

**Comment by Mte90** [comment]
So I created this event https://community.mozilla.org/en/events/this-is-a-test/ from the frontend an I am able to attend it. Someone can test it too?

About past events attending the plugin require a date right now I use the last end date or we can put an year after as date as example but we can remove/ignore that feature.

**Comment by MichaelKohler** [comment]
> So I created this event https://community.mozilla.org/en/events/this-is-a-test/ from the frontend an I am able to attend it. Someone can test it too?

Both clicking that I will attend as well as "unattending" after that worked for me.

> About past events attending the plugin require a date right now I use the last end date or we can put an year after as date as example but we can remove/ignore that feature.

That is great to know. I think we should change it to allow for some time after the event. Maybe a year in the future is too much, but I will let Francesca and Konstantina define that. I would say 6 months would be nice.

**Comment by Mte90** [comment]
So I need a list of events where it isn't happening to understand what is happening (maybe created by different people).

Let's see Francesca/Konstantina says about the expire date.

**Comment by Francescaminelli** [comment]
Hi, Daniele, thank you very much for this. We think one month should be enough time :)

**Comment by Mte90** [comment]
So to move on I need to have events with the issue now as I am not able to replicate the attending issue so I can deploy the code that lock the attending after a month.

**Comment by Francescaminelli** [comment]
Hi Daniele, this has the issue: https://community.mozilla.org/en/events/this-is-another-test/

**Comment by Mte90** [comment]
So in my tests now works.

**Comment by couci** [comment]
Amazing!
Just one feature request, is it possible if the beginning date has passed for the button to change to "I attended "

**Comment by MichaelKohler** [comment]
@Mte90 Thanks for working on this. What is the current status? I just tried it with today's Reps call event, and I couldn't click the button after 15:00 UTC (of course I was once again late).

**Comment by Mte90** [comment]
Link of the event? The code working right now uses 1 month after the date https://github.com/mozilla/community-portal/blob/master/functions.php#L259 with a patch to the event plugin or otherwise is not possible.

So I need the event with the issue because it is just incosistency with DB stuff and that patch should ignore that setting, so without cases to investigate I can't do so much.

**Comment by Mte90** [comment]
So I tried again patching the plugin because seems that my old patch doesn't work anymore.

As we are using the free version their support is not helpful as this require some changes in their plugin. I don't have time anymore to work on this problem.
The problem started when we updated the plugins in the website after 6 months as there was some security issues and they changed some stuff about the RSVP date when is not set like in all the event of the portal.

**Comment by couci** [comment]
adding @craigcook here for visibility

**Comment by Mte90** [comment]
That event doesn't exists.

Anyway I think that at this point as this project is very difficult to manage I think that the easy way should be patch the Event manager plugin directly instead like adding a filter as I did to use in this theme.

**Comment by Mozinet-fr** [comment]
This event **no longer** exists. It still existed on Monday, with the above message. Anyway, many events seem to be gone.

**Comment by Mte90** [comment]
What means to be gone? that was deleted or there are issues and events are disappearing?

**Comment by Mozinet-fr** [comment]
The event dashboard is almost empty for me.
![Screenshot 2022-07-13 at 13-22-05 Dummy Page-red](https://user-images.githubusercontent.com/8845401/178744400-e609f957-4c06-4349-8f08-9b52ae531ac4.png)

**Comment by Mozinet-fr** [comment]
I don't know if it's a different thing or if the event problem is getting worse and worse. I can't tell if it's a database problem or a display problem. In any case, the dashboard was full of events last Monday, at least.

**Comment by Mte90** [comment]
If they are drafts they are not showed on frontend, the status should be published.
It is something that is the case to track in another ticket.

**Comment by Francescaminelli** [comment]
Adding more events in screenshots as examples. As far as I can tell, all future events have been marked as draft: 
![image](https://user-images.githubusercontent.com/58478550/179491842-de445df9-30b1-49e9-a30e-440b1f892eec.png)

**Comment by Francescaminelli** [comment]
It is not possible (again) to sign in to an event (even in the future).

Example, of our Community Call: https://community.mozilla.org/en/events/community-call-01-09-2022/#em-booking

After clicking on "I will attend" nothing happens

**Comment by Mte90** [comment]
I fixed the issue on production patching the plugin.
Now the system is enforcing the closing date for the event end booking date and not the start.

I tested it with various events (also the unattending), can someone else confirm if works?

@Francescaminelli @MichaelKohler @couci

**Comment by couci** [comment]
Tested, works for me

**Comment by siddhartharao17** [comment]
The issue seems to persist.

![image](https://user-images.githubusercontent.com/8169998/223154377-6101e85b-389a-46b6-8e03-8d22439f77f6.png)

**Comment by Mte90** [comment]
Moving to a new ticket as the bug is different.
