### ISSUE TITLE
Getting emails from wordpress?

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#73]
After creating and joining events I keep getting emails like this

![imagen](https://user-images.githubusercontent.com/531906/69337451-275d2c00-0c61-11ea-976b-0b45a6bffe19.png)

I guess we don't want these emails to happen.

**Comment by davesenior** [comment]
@nukeador yes. That's the case. WP-Engine will not support the transactional email volume. It will be disabled

**Comment by nukeador** [comment]
Great, I think it would be good to disable before we get people into the internal QA to avoid confusions.

Thanks! :-D

**Comment by dnaluz** [comment]
I believe emails have been disabled please let me know if you are still receiving them

**Comment by nukeador** [comment]
I haven't received any new emails in a long time.
