### ISSUE TITLE
Logout: Error page

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#74]
When trying to log-out I get this page

![imagen](https://user-images.githubusercontent.com/531906/69340802-8ecaaa00-0c68-11ea-96e9-435d9dfba7ff.png)

**Comment by davesenior** [comment]
Auth0 configuration redirect issue.

**Comment by davesenior** [comment]
will investigate. Suspect it might be because of server password

**Comment by dnaluz** [comment]
Configuration updated and the error no longer appears!
