### ISSUE TITLE
Profile picture not working

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/community-portal#744]
I have set a profile picture:

![image](https://user-images.githubusercontent.com/330324/176740196-15069e3d-fa37-4a49-9fb9-33b5182e2c5d.png)

However, the profile picture does not get rendered, no matter if I'm logged in or not:

![image](https://user-images.githubusercontent.com/330324/176740425-9b056a28-db52-4092-afb1-325880a5e658.png)

**Comment by siddhartharao17** [comment]
Same issue persists for me too

**Comment by Mte90** [comment]
duplicate https://github.com/mozilla/community-portal/issues/743
