### ISSUE TITLE
Single Groups pages are not openinig anymore

### ISSUE THREAD

**Issue by Francescaminelli** [mozilla/community-portal#745]
When clicking on single groups in the Community Portal, you will receive a 404 error message. Examples: 

https://community.mozilla.org/en/groups/codezilla
https://community.mozilla.org/en/groups/mozilla-punjab

**Comment by craigcook** [comment]
This is fallout from disabling WPML (a plugin that was previously adding the /en/ redirect). Working on a fix.

**Comment by craigcook** [comment]
Links should be working again. Sorry about that.
