### ISSUE TITLE
Accessibility: Bad color contrast on hyperlinks in Localize Mozilla page

### ISSUE THREAD

**Issue by reemhamz** [mozilla/community-portal#746]
On the [Localize Mozilla page](https://community.mozilla.org/en/activities/localize-mozilla/), the hyperlinks (notably `Get Started`) have bad color contrasts with the background of the link being nearly similar to the text, providing poor accessibility.

Also, we should remove the space between `Get started` and `!`.

### Suggestion:
- Remove colorful background on hyperlink, or
- change background color to be lighter, providing better color contrast

Check color contrast accessibility here https://webaim.org/resources/contrastchecker/

**Comment by jakobkappel** [comment]
The hyperlinks have been replaced by a button: 

![billede](https://github.com/mozilla/community-portal/assets/3586612/351a94e9-7dd3-4e56-a705-9a1f7b908a77)

Colors contrast (including :hover and :focus) gets a 'Pass' on https://webaim.org/resources/contrastchecker/ 

So I guess the issue can be closed :)
