### ISSUE TITLE
Events: Wording about "bookings"

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#75]
Annonymous users are getting this wording from the events page:

"Please Log In to view your bookings."

I suspect we want something more like "Please Log In to create or join events"

**Comment by davesenior** [comment]
Will implement suggested text

**Comment by davesenior** [comment]
Please log in/sign up to create or join events

**Comment by nukeador** [comment]
There is also an alert box when you click cancel on an event you have RSVP

"Are you sure you want to cancel your booking?"

**Comment by nukeador** [comment]
I think is is solved right?

**Comment by davesenior** [comment]
Yes. Thanks @nukeador
