### ISSUE TITLE
Unable to load newsletter form with uBO Fanboy’s Annoyance list enabled

### ISSUE THREAD

**Issue by dannycolin** [mozilla/community-portal#750]
**Step to Reproduce**

1. Install uBlock Origin (uBO)
1. Open uBO dashboard
1. Go to *Filter lists*
3. Add "Fanboy’s Annoyance" list 
4. Go to https://community.mozilla.org/en/newsletter/

**Actual Behavior**

The main content / newsletter form doesn't load
![image](https://user-images.githubusercontent.com/7339076/204024692-b810077c-a2f4-4f56-baad-be06be3233b7.png)

**Expected Behavior**

Main content should be loaded
![image](https://user-images.githubusercontent.com/7339076/204024726-ae888632-9c9b-4916-a7b3-f7f0b7c04db2.png)

**Comment by couci** [comment]
Hey @dannycolin I think this happens because of the word "subscribe". As I can see here https://easylist.to/easylist/fanboy-social.txt it's part of the general blocking rules, so it makes sense for the content to be blocked

**Comment by dannycolin** [comment]
Oh good catch! I'd have thought that by "annoyance" it'd have been limited to popups and the like, and not broad rules like that.

I'll close this since it's more an easy with the list rules itself than the community portal.
