### ISSUE TITLE
Spam problem on Events

### ISSUE THREAD

**Issue by santiagofn** [mozilla/community-portal#753]
I think the Events page is having a massive problem of spam. I’m seeing a lot of fake events created, e.g.:

 - https://community.mozilla.org/en/events/lemaster-ahmed-pllc/
- https://community.mozilla.org/en/events/browns-pressure-washing-and-roof-cleaning/
- https://community.mozilla.org/en/events/grobuild-construct-group/
- https://community.mozilla.org/en/events/cigaban-yaro-farko/
- https://community.mozilla.org/en/events/digitalis-marketing-ugynokseg/
- https://community.mozilla.org/en/events/clean-energy-group-ai/

I know there’s an option to report an event manually by email, but I think this must be handled in a programmatic way.

**Comment by couci** [comment]
those are now deleted thanks @santiagofn
