### ISSUE TITLE
Groups: Clicking continue to save a group does nothing

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#88]
Go to

https://mdmozdev.wpengine.com/groups/mozillians-valladolid/admin/edit-details/

Modified some description and clicked "Continue"

Nothing happens (same screen). I changed the tags a few times and click continue, nothing.

Went back to the group page and I see the description was saved and I have the same tag displaying twice.

![imagen](https://user-images.githubusercontent.com/531906/69427944-6312f700-0d30-11ea-9583-bd0126c4bf41.png)

**Comment by dnaluz** [comment]
@nukeador sorry was working on something at the moment.  After saving a group it should redirect to the group details page now (non edit).  Will take a look at the tag issue.

**Comment by dnaluz** [comment]
PR https://github.com/mozilla/community-portal/pull/96

**Comment by dnaluz** [comment]
FIx is live
