### ISSUE TITLE
Online groups are listed with a empty location placeholder

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#91]
From a profile

![imagen](https://user-images.githubusercontent.com/531906/69428979-d0278c00-0d32-11ea-957e-16b8b7992cd9.png)

From groups page

![imagen](https://user-images.githubusercontent.com/531906/69429006-dcabe480-0d32-11ea-833e-ef76feb78f7c.png)

**Comment by dnaluz** [comment]
@nukeador this is fixed now
