### ISSUE TITLE
Members: Search not working?

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#94]
Go to https://mdmozdev.wpengine.com/members/

Search for:

ruben
Ruben
Rubén
Ruben

Any of these search are returning my profile

**Comment by dnaluz** [comment]
Currently search only searches by username because that is the only public field available all the time. We have limited search to username.

**Comment by nukeador** [comment]
I suspect this is something we will change to allow people to find based on all the fields they can see, right?

The user cases I see (from mozillians) are:

- I search for a name
- I search for a name and surname
- I search for a surname
- I search for an email
- I filter everyone in country X
- I filter for everyone in city X
- I filter for everyone speaking X language
- I filter for everyone doing X activity (tag)
- I use a combination of filter to find a group that speaks X in country Y and interested in Z

**Comment by davesenior** [comment]
That would be ideal. We are trying to work within the limitations of the platform  (BuddyPress and Wordpress). The custom fields with custom privacy settings are not exposed to the search and filter. I'm going to mark this as a p2 but I agree, functional parity with Mozillians would be nice to have.

**Comment by dnaluz** [comment]
@nukeador @davesenior I think we could look at including searching by first name as it's a simple is logged in check and is already apart of the default Wordpress search.  The other fields would be a lot more complicated because of privacy issues and such.

**Comment by dnaluz** [comment]
After further investigation anywhere we are using an event card or a group card the entire card is a link, so a user cannot click a specific area of a card.  However we can implement this on the individual group and event pages where the tags are listed on the side.

**Comment by dnaluz** [comment]
I've added search by first name in this PR https://github.com/mozilla/community-portal/pull/100.  Searching by subsequent fields that are protected by visibility settings will need a much more complicated function to still return results quickly.  For now I've added first name search

**Comment by dnaluz** [comment]
Ok after further investigation, we will need to change how member search works. The default get_users function doesn't accept first name in the 'search_columns' parameter.  We may be forced to do manual queries if we want to include a more detailed members search

**Comment by dnaluz** [comment]
First name search added
