### ISSUE TITLE
Member: Location placeholder is shown when user is not sharing their email

### ISSUE THREAD

**Issue by nukeador** [mozilla/community-portal#95]
https://mdmozdev.wpengine.com/members/davesenior/

![imagen](https://user-images.githubusercontent.com/531906/69429620-44166400-0d34-11ea-953f-fd6ef412079e.png)

**Comment by dnaluz** [comment]
PR https://github.com/mozilla/community-portal/pull/98

**Comment by dnaluz** [comment]
FIx is live
